openapi-ts/openapi-typescript

src/swagger-2.ts, tests/swagger-2.test.ts
=> Fix camelcased `$ref`s

package-lock.json, package.json
This fixes `npx` installs where Prettier is missing
=> Move Prettier to deps

README.md, bin/cli.js, package-lock.json, package.json
Removes fs-extra to reduce dependency weight for `npx`
=> Remove fs-extra

.github/workflows/pull_request.yml, package.json, src/index.ts, src/types/index.ts, tests/bin/cli.test.ts, tests/bin/prettier.config.js
=> Resolve Prettier config using Prettier

bin/cli.js
=> Remove 2.0 warning

CONTRIBUTING.md, bin/cli.js, examples/stripe-openapi3.ts
Add note on regenerating schemas cc @gr2m
=> Improve CONTRIBUTING.md

src/utils.ts, src/v3.ts, tests/v3/expected/github.ts, tests/v3/index.test.ts
fixes https://github.com/drwpow/openapi-typescript/issues/351
=> test: optional referenced parameters

.github/workflows/pull_request.yml, package-lock.json, package.json
Minor change; just fixes the codecov reports. Also removes the `patch` check as it was just noisy
=> Fix codecov

README.md
=> Correcting Readme Example

bin/cli.js, package-lock.json
Errors now exit with status code `1` instead of `0`. Fixes #423
=> Exit on error code 1

src/types/OpenAPI3.ts, src/v3.ts, tests/v3/index.test.ts
Closes #377 and resolves #378.
Not much to say that isn’t captured in #377.
=> Add test for unknown schema in param

src/v3.ts, tests/v3/index.test.ts
=> Fix additionalProperties.oneOf

src/transform/index.ts, src/transform/operation.ts, src/transform/parameters.ts, src/transform/paths.ts, tests/operation.test.ts, tests/parameters.test.ts, tests/paths.test.ts
Combine some function params into one option object for better DX.
=> Chore: improve function signatures

bin/loaders/index.js, bin/loaders/loadFromHttp.js
=> Get content type from request

jest.config.js, tsconfig.jest.json
Update ts-jest config 🙄 to allow optional chaining
=> Update ts-jest config

.github/workflows/pull_request.yml
Goodnight, sweet Prince. (If you’re on Node 10, update!)
=> Remove Node v10 test

src/transform/responses.ts, src/utils.ts, tests/paths.test.ts
=> Allow schema-less responses

src/index.ts
=> Add prettier/parser-typescript

tests/parameters.test.ts
=> Add nullable params test

package-lock.json, package.json
=> Fix vulnerability (https://npmjs.com/advisories/1677)

README.md, examples/stripe-openapi2.ts, examples/stripe-openapi3.ts
=> chore: README fixes

src/transform/schema.ts, src/utils.ts, tests/schema.test.ts, tests/v3/expected/github.additional.ts, tests/v3/expected/github.immutable.ts, tests/v3/expected/github.ts
=> fix: properties + anyOf with only required properties

.github/workflows/pull_request.yml, package-lock.json, package.json, src/load.ts, tests/bin/cli.test.ts, tests/test-utils.ts, tests/v2/index.test.ts, tests/v3/index.test.ts
We might be getting some Windows bugs causing #638. But it’s probably also good to just start testing Windows in general. 
This PR adds Windows testing to GitHub Actions.
=> Add Windows test in CI

bin/cli.js, package-lock.json, package.json, src/load.ts
=> Chore: update deps

test/bin/cli.test.js, test/opts/expected/remote-schema.ts, test/opts/fixtures/remote-schema/spec.yml, test/v2/index.test.js, test/v3/index.test.js
Fixes remote spec URL from `/tests/` rename in #842
=> chore: Fix remote tests

src/transform/schema.ts, test/core/schema.test.js
=> Fix required additional properties

.eslintrc.cjs, .github/workflows/ci.yml, package.json, src/index.ts, src/load.ts, src/transform/index.ts, src/transform/parameters.ts, src/transform/schema.ts, src/utils.ts, test/core/operation.test.js, test/core/parameters.test.js, test/core/paths.test.js, test/core/request.test.js, test/core/schema.test.js, test/opts/empty-definitions.test.js, test/opts/formatter.test.js, test/opts/raw-schema.test.js, test/opts/remote-schema.test.js, test/v2/index.test.js, test/v3/index.test.js
Add `eslint:recommended` to lint rules, remove some rule overrides
=> Tighten lint rules

.github/workflows/ci.yml, package.json
Removes `"postinstall"` hook from package.json
N/A
=> Remove postinstall hook

CONTRIBUTING.md
Fixes the URL to an external link in the README.
Check that the new link works ok 🙂
=> Fix link in README

src/load.ts
Minor QoL improvement for invalid schemas. Though this library won’t support schema validation, there are some common errors that can be prevented. A couple error checks added to the first pass of the schema, which is a common failure point for invalid schemas.
=> Improve error in load.ts parsing

README.md
Encourage best-practices by considering nullable properties in the transform function.
Consider whether the extra complexity is warranted.
- 🚫 Unit tests updated
- 🚫 `examples/` directory updated (if applicable)
=> docs: Update transform date-time example

src/transform/schema-object.ts, src/types.ts, test/schema-object.test.ts
=> fix: tuples type generation support (#1011)

examples/digital-ocean-api.ts, examples/github-api.ts, examples/stripe-api.ts, examples/stripe-api.yaml, src/index.ts, src/load.ts, src/utils.ts, test/fixtures/remote-ref-test-2.yaml, test/fixtures/remote-ref-test.yaml, test/index.test.ts
Fixes #1041. The test suite only included examples of partial schemas for remote $refs, so complete schemas were broken. This supports complete remote schemas; there was just a bug in parsing. This fixes that issue and adds a test.
Tests cover the changes; tests should pass.
=> Fix remote $refs to complete schemas

packages/openapi-fetch/README.md
=> Fix README img

packages/openapi-fetch/README.md
Removes redundant openapi-fetch README title
=> Readme title

packages/openapi-fetch/CHANGELOG.md, packages/openapi-fetch/src/index.ts
Copies changes from https://github.com/drwpow/openapi-fetch/pull/45
=> Fix post() and options() types

docs/astro.config.mjs, docs/package.json, docs/src/components/Header/Search.tsx, pnpm-lock.yaml
Passes Algolia env vars to get docs site search working. Docs-only change.
=> Fix Algolia env vars

.github/workflows/release.yml
Fixes accidental YAML indentation error (bad copy/paste)
=> Fix Actions indentation

.github/workflows/release.yml, docs/src/content/docs/about.md, packages/openapi-typescript/README.md
Minor docs improvement; no code changes
=> Add Redocly to docs

.github/workflows/release.yml, packages/openapi-fetch/package.json, packages/openapi-typescript/package.json
=> Change release action

packages/openapi-fetch/CHANGELOG.md
Fixes Changelog version caused from a migration error. No code changes.
=> Fix openapi-fetch changelog

.changeset/eighty-chairs-join.md
I’d consider b82cffb to be a patch rather than a minor release as it was mostly a bugfix. No other changes.
=> Change minor change to patch

docs/package.json, docs/src/content/docs/openapi-fetch/api.md, docs/src/content/docs/openapi-fetch/index.md, packages/openapi-fetch/README.md, packages/openapi-fetch/src/index.test.ts, packages/openapi-fetch/test/v1.d.ts, packages/openapi-fetch/test/v1.yaml, packages/openapi-typescript/examples/digital-ocean-api.ts, packages/openapi-typescript/examples/digital-ocean-api/DigitalOcean-public.v2.yaml, packages/openapi-typescript/examples/digital-ocean-api/resources/databases/databases_add_user.yml, packages/openapi-typescript/examples/digital-ocean-api/resources/databases/examples/curl/databases_update_firewall_rules.yml, packages/openapi-typescript/examples/digital-ocean-api/resources/volumes/models/volume_base.yml, packages/openapi-typescript/examples/github-api.ts, packages/openapi-typescript/examples/stripe-api.ts, packages/openapi-typescript/examples/stripe-api.yaml, pnpm-lock.yaml
Docs-only change: In tests and docs, changes `.get('/post')` to `.get('/blogposts')` because the former is confusing to read for the first time.
=> Change .get('/post') as it’s confusing

packages/openapi-typescript/src/types.ts
Fixes #1062. Internal fix only; no actual code changes.
N/A
N/A
=> Fix MediaTypeObject encoding type

docs/src/content/docs/openapi-fetch/examples.md
Docs-only change; makes minor improvement to React Query example.
N/A
N/A
=> Update React Query example

.changeset/chilled-swans-hunt.md, packages/openapi-typescript/examples/digital-ocean-api.ts, packages/openapi-typescript/examples/octokit-ghes-3.6-diff-to-api.ts, packages/openapi-typescript/examples/stripe-api.ts, packages/openapi-typescript/src/transform/components-object.ts, packages/openapi-typescript/src/transform/operation-object.ts, packages/openapi-typescript/test/components-object.test.ts, packages/openapi-typescript/test/index.test.ts, packages/openapi-typescript/test/operation-object.test.ts, packages/openapi-typescript/test/paths-object.test.ts
(Might fix) #1340. Updates parameter optional behavior to not affect the components object; instead only happening on individual operation objects.
- Tests updated; tests should pass.
=> Fix all parameters optional

docs/src/components/LeftSidebar/LeftSidebar.astro
Docs-only issue; fixes issue with currently-highlighted page. No runtime code affected.
N/A
N/A
=> Fix current page highlight in docs

docs/src/content/docs/about.md
Docs-only change; fixes malformed “Supabase” formatting
N/A
N/A
=> Fix docs formatting

packages/openapi-typescript/README.md
This PR change is related to fix advanced.md link for **openapi-typescript** package.
Just check the path of advanced.md which is required to link for **openapi-typescript** package.
=> fix advanced.md doc link for openapi-typescript's Readme.md file

.changeset/chilly-cheetahs-attack.md, packages/openapi-fetch/CHANGELOG.md, packages/openapi-fetch/package.json
=> openapi-fetch@0.8.0

.gitignore, README.md, docs/.vitepress/config.ts, docs/6.x/advanced.md, docs/6.x/introduction.md, docs/README.md, docs/advanced.md, docs/introduction.md
Docs-only change; fixes Vitepress build.
N/A
N/A
=> Fix docs build

docs/.vitepress/config.ts
Docs-only change: adds sitemap.xml to docs
N/A
N/A
=> Add sitemap

.changeset/fair-carpets-beg.md, .changeset/twelve-gifts-sort.md, packages/openapi-fetch/CHANGELOG.md, packages/openapi-fetch/package.json, packages/openapi-typescript-helpers/CHANGELOG.md, packages/openapi-typescript-helpers/package.json, pnpm-lock.yaml
Releases openapi-fetch@0.8.2, openapi-typescript-helpers@0.0.5
N/A
N/A
=> openapi-fetch@0.8.2

.changeset/nine-pigs-reply.md, packages/openapi-typescript-helpers/index.d.ts
Add `RequestBodyJSON` helper for openapi-typescript-helpers
- Unused helper internally
N/A
=> Add RequestBodyJSON helper

docs/.vitepress/config.ts, docs/package.json, pnpm-lock.yaml
Fixes typo in Vitepress config for the URL.
=> Fix docs hostname

pnpm-lock.yaml
Fixes failing CI from frozen lockfile.
N/A
N/A
=> [Chore] Fix lockfile

docs/.vitepress/zh.ts, docs/openapi-fetch/api.md, docs/scripts/update-contributors.js, docs/zh/about.md, docs/zh/advanced.md, docs/zh/examples.md, docs/zh/openapi-fetch/about.md, docs/zh/openapi-fetch/api.md, docs/zh/openapi-fetch/examples.md, docs/zh/openapi-fetch/index.md, docs/zh/openapi-fetch/middleware-auth.md, docs/zh/openapi-fetch/testing.md
Complete 'openapi-typescript' documentation in Chinese
=> Translate openapi-typescript for Chinese

.changeset/unlucky-pumpkins-march.md, packages/openapi-fetch/CHANGELOG.md, packages/openapi-fetch/package.json
Manual release needed for changeset
=> openapi-fetch@0.9.3

docs/introduction.md
=> Add “intro to OpenAPI” link

.changeset/config.json, .github/workflows/ci.yml, .github/workflows/release.yml, docs/package.json, package.json, packages/openapi-fetch/examples/nextjs/package.json, packages/openapi-fetch/examples/react-query/package.json, packages/openapi-fetch/examples/sveltekit/package.json, packages/openapi-fetch/package.json, packages/openapi-typescript-helpers/package.json, packages/openapi-typescript/package.json, packages/openapi-typescript/test/invalid.test.ts, packages/openapi-typescript/test/yaml.test.ts, pnpm-lock.yaml
Chore; updates 6.x branch’s CI to allow for an easier bugfix & release
- CI Should pass
N/A
=> Update 6.x deps

packages/openapi-typescript/package.json
Chore: updates 7.x package.json to release candidate status. No other changes. 
N/A
N/A
=> Release Candidate

packages/openapi-typescript/.npmignore
Chore: removes some local/dev TSConfig files from the npm package to reduce noise.
N/A
N/A
=> Clean up unnecessary files from npm package

docs/zh/node.md
=> fix: doc typo

.github/workflows/release.yml
Add the `write` scope to the `GITHUB_TOKEN` stored.
N/A
=> Add Actions permissions

.github/workflows/release.yml
Another test to fix the changesets action
=> chore: Improve Actions permissions

packages/openapi-fetch/package.json
Publishes `openapi-fetch@0.10.0`.
N/A
=> openapi-fetch@0.10.0

docs/introduction.md
Fixes a sentence by closing an open parenthesis.
=> docs: add missing )

CONTRIBUTING.md
Adds `CONTRIBUTING.md` to root as a suggestion to look in other packages
Internal change; N/A
N/A
=> Chore: Add monorepo Contributing guide

packages/openapi-typescript/bin/cli.js
Remove unwanted curly bracket in generated filename.
=> Remove unwanted curly bracket in generated filename

README.md
Chore: Updates Zuplo’s README link
N/A
N/A
=> chore: Update README link

docs/ja/migration-guide.md, docs/migration-guide.md
Updated the CHANGELOG URL in the migration guide
=> docs: Update Migration Guide URL

docs/cli.md, docs/ja/cli.md, docs/zh/cli.md
=> docs: fix examples

packages/openapi-fetch/examples/nextjs/package.json, pnpm-lock.yaml
Updates Next.js to 15 in example, also removing security vuln warnings
N/A
N/A
=> Chore: Update Next.js

packages/openapi-typescript-helpers/package.json, packages/swr-openapi/package.json, pnpm-lock.yaml
Getting a CI failure on `main` with a lockfile mismatch. Not sure what the issue is, but going to try and clean up some minor package inconsistencies.
No runtime code affected.
N/A
N/A
=> Chore: consolidate dep versions, update lockfile

docs/openapi-metadata/index.md
=> fix(docs): fix a typo

docs/package.json, package.json, packages/openapi-fetch/examples/nextjs/package.json, packages/openapi-fetch/package.json, packages/openapi-react-query/package.json, packages/openapi-typescript/package.json, packages/swr-openapi/package.json, pnpm-lock.yaml
Followup to #2270. Had a bad merge conflict that resulted in a few unexpected versions. No effects though.
N/A
- CI will show any errors
=> chore: update deps (2)
