src/swagger-2.ts

Enum values can be more than one word, so replace whitespace so that enum names are valid

Remove spaces in enum names

---

example/input.yaml
example/output.ts
src/swagger-2.ts
tests/swagger-2.test.ts

This PR adds supports for object definitions with `additionalProperties: boolean | Swagger2Definition`

Create interfaces for additionalProperties objects

---

example/output.ts
src/swagger-2.ts
tests/swagger-2.test.ts
tsconfig.json

Top-level Array types can’t be TypeScript Interfaces, so they should be ignored.
While there may be some practical usecase where this causes issues, at least for our internal specs, all our top-level array specs are referenced elsewhere, and handled correctly.
If this breaks someone’s specific usecase, the solution can be modified.

Ignore top-level array definitions

---

src/swagger-2.ts
tests/swagger-2.test.ts

Adds missing test for new export option

Add export option test

---

README.md
bin/cli.js
example/output.d.ts
package-lock.json
package.json
src/swagger-2.ts
tests/index.test.ts
tests/swagger-2.test.ts

It’s getting hard to support all the ways to expose these types. This adds the amazing `--wrapper` option that lets you do things like `--wrapper "export namespace MyNamespace"` or `--wrapper "declare module '@api'"`. More details in the README.
Deprecates `--namespace` and `--export` flags in favor of something more versatile.

Add wrapper option

---

src/swagger-2.ts
tests/swagger-2.test.ts

Handle kebab-cased names

---

README.md
package-lock.json
package.json

Fixes some typos, shortens a few sentences.

README changes

---

.eslintrc.js
package-lock.json
package.json
src/swagger-2.ts
tests/swagger-2.test.ts

When using nested objects, it wouldn’t transform underscores properly. Given:
```yaml
properties: {
remote_ids: {
type: 'object', properties: { id: { type: 'string' } } },
},
},
```
it would return the following interface:
```ts
interface UserRemote_ids {} // 🚫
```
This now returns the following, as expected:
```ts
interface UserRemoteIds {} // ✅
```

Fix underscores in interface names

---

README.md
bin/cli.js
src/swagger-2.ts
tests/index.test.ts

I would rather that the default behavior be no wrapper, but that would be a breaking change. 
Of course, I'm open to any other way to make `wrapper` optional

Optional wrapper

---

src/swagger-2.ts
tests/swagger-2.test.ts

Fix nested arrays

---

example/nowrapper.ts
example/output.d.ts
src/swagger-2.ts

Instead of having regular comments. Let's use jsdoc comments.
closes #57

feat(doc): prints out jsdoc

---

src/swagger-2.ts
tests/swagger-2.test.ts

Should hopefully close https://github.com/manifoldco/swagger-to-ts/issues/66

Convert names containing spaces to use underscores

---

README.md
src/index.ts
src/swagger-2.ts
tests/swagger-2.test.ts

As discussed in #77 .
Had to change the logic in properties handling a bit, and introduced a new interface Properties. In addition, the Swagger2Definition interface is now exported from the top-level, as it is used in the mapper. 
New tests added for the new functionality, all existing tests still passes. Readme is also updated. 
Comments and suggestions welcome.

Property mapper function

---

src/utils.ts
tests/utils.test.ts

This is not a scalable solution, but it's quite common for some fields to be prefixed with `@`.

fix(utils/sanitize): Take into account the at sign

---

.github/workflows/pull_request.yml
package.json
src/types/OpenAPI2.ts
src/v2.ts

Another chore for OpenAPI v3. This doesn’t affect Swagger v2; just provides a minor type change in preparation for v3

Add SchemaReference type

---

package.json

This is useful to avoid prettier to pick up global prettier config in case it is different from what is used in the project.

add default default prettier config

---

src/property-mapper.ts
src/utils.ts
src/v2.ts
src/v3.ts
tests/bin/cli.test.ts
tests/bin/expected/petstore.ts
tests/utils/index.test.ts
tests/v2/expected/http.ts
tests/v2/expected/manifold.ts
tests/v2/expected/petstore.ts
tests/v2/expected/stripe.ts
tests/v3/expected/manifold.ts
tests/v3/expected/petstore.ts
tests/v3/expected/stripe.ts

Ditches the `JSON.parse()` approach which was limiting in 2 major ways:
- Couldn’t add `nullable` support (#112)
- Couldn’t add support for comments (now added! 🎉 )
At the end of the day, TypeScript isn’t JSON 🤷. And it turns out the original codebase was closer to what it needed to be. This PR refactors the output generation a little to be _even simpler_ than before.

Transform recursively, without JSON.parse()

---

package.json
src/types/OpenAPI2.ts
src/types/OpenAPI3.ts
src/utils.ts
tests/v2/index.test.ts
tests/v3/index.test.ts

Many schemas omit information because the OpenAPI spec allows (such as omitting `type: object' or `type: array' and inferring from other properties). This adds _robustity_ to handle that.

Improve array and object handling

---

bin/cli.js

Adds the following warning with the `2.0` release:

Add 2.0 warning

---

src/types/OpenAPI3.ts
src/v3.ts
tests/v3/expected/petstore.ts
tests/v3/specs/petstore.yaml

I'm using Typescript on both the client and server side to strictly type my API requests / responses, and the [Swagger components section](https://swagger.io/docs/specification/components/) includes suggested usage of the `components.responses` key.
This adds the support with as little ceremony as possible (responses isn't required, property mapping is only used for schemas, no changes to schemas usage, etc.). If you'd like it to be generalized a bit more to encourage mapping more pieces of the Swagger spec, happy to do so.

Support for components.responses

---

examples/stripe-openapi2.ts
examples/stripe-openapi3.ts
src/v2.ts
src/v3.ts
tests/v2/expected/http.ts
tests/v2/expected/manifold.ts
tests/v2/expected/stripe.ts
tests/v3/expected/stripe.ts
tsconfig.json

if `additionalProperties` is not of a primitive type, the generated file will contain things like `ref` or `array` instead of interpolating that ref or array.  this PR should fix that and #265.
not aware of any side effects, let me know if you can think of any.

additionalProperties interpolation, primitive enums

---

bin/cli.js
bin/loaders/index.js

Two small things:
1) If you fail to load the spec, then return early. Otherwise the `swaggerToTS` function will attempt to execute and obviously fail, giving you a misleading error message
2) Bubble up the error message returned from `yaml.safeLoad()` to give you an idea of why the script is failing
Before:
After:

bubble up the error message / improve error message when failing to parse the schema

---

bin/loaders/index.js

This change improves the error message for when the remote file you're trying to access is unreachable. This can happen if you misspelled the URL, the server is down for some reason or if you don't have access to the internet.

Improve error message when server is unreachable

---

src/utils.ts
src/v3.ts
tests/v3/index.test.ts

This PR adds support for openapi v3's tuples

Add tuple support

---

bin/cli.js
src/index.ts
src/types/OpenAPI2.ts
src/types/OpenAPI3.ts
src/types/index.ts
src/utils.ts
src/v2.ts
src/v3.ts

This adds support for supplying raw v3 schemas or v2 definitions as an alternative to supplying full Swagger/OpenAPI documents, using an option `--raw-schema` in combination with `--version`.
Previously, swagger-to-ts would require `components` to be present in the given document, even though it's an optional property. When dealing with large documents, it's common practice to
split it over several files, putting e.g. schemas in separate files.
This change enables producing types for such stand-alone schemas by adding an option to parse the given file as a map of schemas  rather than a document. For this to work, the version must also be passed since it's not present in raw schemas/definitions.
For example, if the full document is:
```
openapi: 3.0.2
components:
schemas:
Foo:
type: object …
```

Support raw schemas in addition to Swagger/OpenAPI documents

---

src/types/OpenAPI3.ts
src/utils.ts
src/v3.ts

cause that is what it is: https://swagger.io/docs/specification/paths-and-operations/

refactor: rename internal `responses` variable to `operation`

---

src/utils.ts

both my PRs #334 and #335 failed because of a new eslint rule. I thought you might want to merge this in first in case the PRs get blocked. I added the same commit to the PRs to get them to green

style: make eslint happy

---

src/types/OpenAPI3.ts
src/v3.ts
tests/bin/expected/petstore.ts
tests/v3/expected/github.ts
tests/v3/expected/manifold.ts
tests/v3/expected/petstore.ts
tests/v3/expected/stripe.ts
tests/v3/index.test.ts

This PR combines the other separate PRs I opened. If you want to merge them all, merging this one is the easiest way, as there are some merge conflicts
closes #337 
closes #339
fixes #329
fixes #338

feat: `requestBody`, `$ref`-type parameters

---

src/v3.ts
tests/v3/expected/github.ts
tests/v3/index.test.ts

Here is a minimal test case to reproduce the problem: [TypeScript Playground](
https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwoF4oG8BQVtQJb3gFcEB+ALikQCdcA7AcwG4scBjACwlYGt5zLgNBsxxQAthGABDACZTp-anSYtsrAPa1gELXwpLhqqDIhgANupATdiwcpE4A2twgh9dhgF13QlQF8gA)
This feels like a potential TypeScript bug to me, what do you think? But basically this comes down to:
- If a schema is of type `object`
- and it has `additionalProperties`
- then instead of adding `[key: string]: string;` to the object, we should create an intersection with a separate `{ [key: string]: string; }` object
Result: [TypeScript Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwoF4oG8BQVtQJb3gFcEB+ALikQCdcA7AcwG4scBjACwlYGt5zLgNBsxxQAthGABDACZTp-anSYtsrAPa1gELXwpLhqqDIhgANupATdiwcuYBfKADJ0UANrcIIfXY …

Set index type to all possible values

---

src/types/OpenAPI3.ts
src/v3.ts
tests/v3/index.test.ts

Factors out generating the parameters block into a `parseParameters` function.
Calls it both on operations, and also on the parameters block at the path level if one was given.
Prevents the parameters block being parsed as a method.
Fixes #346

Handle parameters on paths as well as methods

---

src/utils.ts
tests/v2/index.test.ts
tests/v3/index.test.ts

Partial workaround for #321. Converts `$ref: 'foo.yaml#bar'` to `any` for now.

Fix external $refs

---

src/v3.ts
tests/v3/expected/github.ts
tests/v3/index.test.ts
tests/v3/specs/github.yaml

I've run into this problem when updating to the latest GitHub schema, this PR reproduces the problem the same way. I'm looking into fixing it
fixes #256

fix: escape quotes in enum string values

---

src/types/OpenAPI3.ts
src/v3.ts
tests/v3/index.test.ts

Fixes issue #360
* Adds a check `isMethod` in `transformPaths` in [./src/v3.ts](./src/v3.ts)
* Adds a new `OpenAPI3PathItemObject` type in [./src/types/OpenAPI3.ts](./src/types/OpenAPI3.ts)
* This added type `OpenAPI3PathItemObject` is per "PathItemObject" spec <https://swagger.io/specification/#path-item-object>
* Replaces the key-value pair in `OpenAPI3Paths`
* `OpenAPI3PathItemObject` *is* missing the `servers` field from the specs
* Variable name bikeshedding - changed `method` to `field` since it *might not* be a method
*Edit*: updated type to `OpenAPI3PathItemObject` from `OpenAPI3PathItem`

fix: check if path item is method operation

---

src/types/OpenAPI3.ts
src/v3.ts

I spotted that this caused failures for our OpenAPI files being generated.
In general, I think that `OpenAPI3.ts` should be replaced with something like https://www.npmjs.com/package/atlassian-openapi so that the types are more reliable and thus the logic is more correct.

Fixing 'content' being expected to be present.

---

examples/stripe-openapi3.ts
src/types/OpenAPI3.ts
src/v3.ts
tests/bin/expected/petstore.ts
tests/v2/specs/stripe.yaml
tests/v3/expected/github.ts
tests/v3/expected/manifold.ts
tests/v3/expected/petstore.ts
tests/v3/expected/stripe.ts
tests/v3/index.test.ts
tests/v3/specs/github.yaml
tests/v3/specs/stripe.yaml

make status codes numeric

---

.prettierignore
jest.config.js
package.json

I've noticed prettier is not being followed. This PR formats all JS/TS files according to the prettier config and removes YAML files from the prettier scope as it was apparently not being used for such files at all.

apply prettier

---

src/types/OpenAPI2.ts
src/utils.ts
src/v2.ts
tests/v2/index.test.ts

Fixes #345 
As stated in the comment, the functionality in getAdditionalPropertiesType could perhaps be added in nodeType, but then I had to pass in the rawDefinition there, and risk messing up things.
This seems to work, added a new tests based on the inut in #345, both this and all old tests pass

handle case where additionalRef is a ref (fixes #345)

---

bin/cli.js
bin/loaders/index.js
codecov.yml
package-lock.json
package.json

While this doesn’t get rid of the dependency altogether (some of our `devDeps` need it), it at least removes it from our codebase directly as a runtime dependency.

Replace chalk with kleur

---

src/v2.ts
tests/v2/index.test.ts

Applying the same fix on V3 as V2.
Ref: https://github.com/drwpow/openapi-typescript/pull/365

Escape Enums in V2

---

package-lock.json
package.json
src/types/OpenAPI3.ts
src/v3.ts
tests/v3/expected/github.ts
tests/v3/expected/petstore.ts
tests/v3/index.test.ts
tests/v3/specs/petstore.yaml

Fixes #408
Before we were skipping detailed responses with `unknown` or `{ [key: string]: any }`. This adds proper support for responses, as requested in #408. Tests have been updated to reflect the new generation.

Add support for components.responses

---

examples/stripe-openapi2.ts
examples/stripe-openapi3.ts
src/utils.ts
src/v2.ts
src/v3.ts
tests/bin/expected/prettier-js.ts
tests/bin/expected/prettier-json.ts
tests/bin/expected/stdout.ts
tests/v2/expected/http.ts
tests/v2/expected/manifold.ts
tests/v2/expected/petstore.ts
tests/v2/expected/stripe.ts
tests/v2/index.test.ts
tests/v3/expected/github.ts
tests/v3/expected/http.ts
tests/v3/expected/manifold.ts
tests/v3/expected/petstore.ts
tests/v3/expected/stripe.ts
tests/v3/index.test.ts

Followup to #443. Apparently when you have:
```js
{ /** comment */ property: … }
```
Prettier will keep the comment and property on the same line. This PR enforces a newline after `{`, resulting in:
```diff
address: {
-   /** City, district, suburb, town, or village. */ city?: string;
+  /** City, district, suburb, town, or village. */
+  city?: string;
```
Unfortunately in the process, it does enforce that every object’s properties are on their own lines. Overall, though, I think it’s a good tradeoff.

Fix single-line comments

---

src/transform/operation.ts
src/types/index.ts

Adding support for refs in operation `requestBody` to support the `components.requestBodies` objects.
I looked through tests and didn't see where would be most appropriate to test this - it didn't look like anything besides schemas and parameters were tested in the example files, and many tests were GH issue-based. Let me know, happy to add testing.

Request body refs

---

src/transform/index.ts
src/transform/operation.ts
src/transform/responses.ts
tests/operation.test.ts
tests/v3/expected/petstore-openapitools.ts

According to [OpenAPI 3.0](https://swagger.io/docs/specification/describing-request-body/#Reusable%20Bodies) `components.requestBodies` have a specific schema:
```yaml
components:
requestBodies:
PetBody:
description: A JSON object containing pet information
required: true
content:
application/json:
schema:
$ref: '#/components/schemas/Pet'
```
Currently `components.requestBodies` is transformed as normal schema with the wrong output code:
```typescript
requestBodies: {
/** List of user object */
UserArray: { [key: string]: any };
/** Pet object that needs to be added to the store */
Pet: { [key: string]: any };
};
```
This PR fix wrong transformation, and makes ability to have a valid output code:
```typescript
requestBodies: {
/** List of user object */
UserArray: {
content: { …
```

WIP: Adding requestBodies transform support

---

src/transform/schema.ts
src/utils.ts
tests/schema.test.ts
tests/v3/expected/github.ts
tests/v3/specs/github.yaml

follow up to https://github.com/octokit/types.ts/issues/274 and https://github.com/github/rest-api-description/issues/220

fix: schema with `properties` and `oneOf` properties

---

README.md
bin/cli.js
bin/loaders/index.js
bin/loaders/loadFromFs.js
bin/loaders/loadFromHttp.js
package-lock.json
package.json

Part of #505 and #507.
Improves the error message given when a bad URL is encountered, and adds the `--auth` flag for passing basic authentication to a protected schema. It simply passes the value to Node’s [http.request’s auth option](https://nodejs.org/api/http.html#http_http_request_url_options_callback).

Improve remote specs

---

bin/loaders/index.js
bin/loaders/loadFromHttp.js

This PR adds 3xx redirect following, which was previously unsupported.
Also fixes an unreleased contentType bug from #508.

Follow 3xx redirects

---

src/transform/schema.ts
tests/schema.test.ts

Fixes #504 
As stated in the [documentation ](https://swagger.io/docs/specification/data-models/dictionaries/) Freeform objects (objects with any value) can be defined by setting additionalProperties either to true or {}. 
Previously:
```
foo?: { [key: string]: { [key: string]: any } }
```
was the output instead of:
```
foo?: { [key: string]: any }
```
This is fixed and tested with this PR.

504 - Fix additionalProperties on object type

---

src/transform/index.ts
src/transform/operation.ts
src/transform/paths.ts
tests/operation.test.ts
tests/paths.test.ts

A path item may declare common parameters to all operations outside of the operation map.
If this is the case, all operations should inherit those parameters and merge them with
any operation specific parameters.
In case of conflicting parameters, the one defined in the operation has precedence over
path item parameters.
To fix this, operations need a reference to their path item, so modifying the record of operations built during path item parsing to hold { operation, pathItem } objects.

Inherit parameters from path item to its operations.

---

.github/workflows/pull_request.yml

fixes: https://github.com/drwpow/openapi-typescript/pull/530#discussion_r599828545
also included node.js v15
v10 can probably dropped end-of-April: https://nodejs.org/en/about/releases/ and replaced with v16 (while v15 to be removed)

ci: use node.js version from matrix

---

src/utils.ts
tests/utils/index.test.ts

This avoids accidental closing of comment tags.
Fixes #547

Escapes markdown descriptions

---

src/transform/responses.ts
tests/operation.test.ts

If a request body's name is hypenated it breaks when prettier formats the code as it is an invalid object.
Wrapping the request body's name in quotes resolves the issue, and prettier will strip the quotes when they're not required.
```
npx openapi-typescript https://raw.githubusercontent.com/ashsmith/api-specs/fix-invalid-examples/reference/channels.v3.yml --output channels.v3.ts
```
```
SyntaxError: Property or signature expected. (505:7)
503 |   }
504 |   requestBodies: {
> 505 |       post-channels-channel_id-currency-assignmentsBody: {    content: {
|       ^
506 |       "application/json": {
507 | /** Currencies that are enabled for the given channel, in ISO 4217 3 character alphabetic */
508 | "enabled_currencies": (string)[];
at e …
```

Fix requestBodies that use hypenated naming

---

src/transform/headers.ts
src/transform/index.ts
src/transform/operation.ts
src/transform/parameters.ts
src/transform/responses.ts
src/transform/schema.ts
tests/bin/expected/prettier-js.ts
tests/bin/expected/prettier-json.ts
tests/bin/expected/stdout.ts
tests/operation.test.ts
tests/paths.test.ts
tests/raw-schema.test.ts
tests/schema.test.ts
tests/v3/expected/github.immutable.ts
tests/v3/expected/github.ts
tests/v3/expected/http.ts
tests/v3/expected/manifold.immutable.ts
tests/v3/expected/manifold.ts
tests/v3/expected/null-in-enum.immutable.ts
tests/v3/expected/null-in-enum.ts
tests/v3/expected/petstore-openapitools.immutable.ts
tests/v3/expected/petstore-openapitools.ts
tests/v3/expected/petstore.immutable.ts
tests/v3/expected/petstore.ts
tests/v3/expected/stripe.immutable.ts
tests/v3/expected/stripe.ts

Resolves #583 . Let me know if this seems correct or if you have any comments/critiques!
Signed-off-by: Micah Halter <micah@balena.io>

Fixed openapi 3 spec to default additionalProperties to true

---

src/transform/schema.ts
src/types.ts
tests/bin/expected/prettier-js.ts
tests/bin/expected/prettier-json.ts
tests/bin/expected/stdout.ts
tests/v2/expected/http.ts
tests/v2/expected/manifold.immutable.ts
tests/v2/expected/manifold.ts
tests/v2/expected/petstore.immutable.ts
tests/v2/expected/petstore.ts
tests/v3/expected/github.additional.ts
tests/v3/expected/github.immutable.ts
tests/v3/expected/github.ts
tests/v3/expected/http.ts
tests/v3/expected/manifold.additional.ts
tests/v3/expected/manifold.immutable.ts
tests/v3/expected/manifold.ts
tests/v3/expected/petstore-openapitools.additional.ts
tests/v3/expected/petstore-openapitools.immutable.ts
tests/v3/expected/petstore-openapitools.ts
tests/v3/expected/petstore.additional.ts
tests/v3/expected/petstore.immutable.ts
tests/v3/expected/petstore.ts

Partially fixes #584.
This is a very good fix pointed out by @rustyconover, and handled in PR #584, but that currently would be blocking remote schemas, as `$ref`s would no-longer be resolvable (or at least, not easily). This PR does half of #584, where `$ref`s are not resolved. But it does improve the handling of `default: ` without blocking remote schemas.

Mark schema objects with default values as non-nullable

---

.gitignore
README.md
bin/cli.js
tests/bin/cli.test.ts
tests/v2/index.test.ts
tests/v3/index.test.ts

Adds glob docs to README, (#616), along with credit.
Also fixes an unreleased bug where specifying a glob pattern wouldn’t create the folder (it used the file behavior, where it would stop at the _parent_ directory, as with single files, however with globs we need that last directory, too)

Add docs for glob feature to README

---

bin/cli.js
package.json

The latest glob changes would accidentally make an empty directory when loading a single file. While technically not breaking, it’s annoying. This fixes that.

Fix generation of empty directory

---

README.md

I came across `for obvious reasons` but then I realized that it wasn't very obvious to me. I wanted to make sure it's easier for others to understand in the future.
I replaced it with the reason why I believe this might be the reason, but I could be wrong. If I'm wrong, please suggest the actual reason so I can update it.

Add an explicit description of reason why remote globbing doesn't work

---

src/index.ts
src/load.ts
tests/v2/index.test.ts
tests/v3/index.test.ts

Fixes #638. In the 4.0 update that supports remote schemas, `$ref`s have to be parsed upfront before anything else is transformed to know which schemas to fetch. But when passing in JSON, the $refs were accidentally skipped.
This PR also adds a test for the JS API to ensure it doesn’t break again.

Fix JSON loader

---

.npmrc
package.json

Hey,
There is a small patch to strictly requires npm 7 to install dependencies.
Users with lower npm versions will get error message like this:
```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for openapi-typescript@4.0.2: wanted: {"node":">= 12.0.0","npm":">= 7.0.0"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm ERR! notsup Not compatible with your version of node/npm: openapi-typescript@4.0.2
npm ERR! notsup Not compatible with your version of node/npm: openapi-typescript@4.0.2
npm ERR! notsup Required: {"node":">= 12.0.0","npm":">= 7.0.0"}
npm ERR! notsup Actual:   {"npm":"6.14.8","node":"14.15.0"}
```
Refs:
- https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines
- https://docs.npmjs.com/cli/v7/using-npm/config#engine-strict

Strictly requires npm 7.0

---

src/transform/schema.ts
src/utils.ts
tests/schema.test.ts
tests/v2/expected/petstore.immutable.ts
tests/v2/expected/petstore.ts

Related to https://github.com/drwpow/openapi-typescript/issues/726. When `type: "file"` is encountered in parameters, weird results occur.

Feat: add support for "type": "file" in parameters

---

examples/stripe-openapi2.ts
examples/stripe-openapi3.ts
src/transform/schema.ts
src/utils.ts
tests/request.test.ts
tests/schema.test.ts
tests/v2/expected/stripe.immutable.ts
tests/v2/expected/stripe.ts
tests/v3/expected/github.additional.ts
tests/v3/expected/github.immutable.ts
tests/v3/expected/github.ts
tests/v3/expected/manifold.additional.ts
tests/v3/expected/null-in-enum.additional.ts
tests/v3/expected/petstore-openapitools.additional.ts
tests/v3/expected/petstore.additional.ts
tests/v3/expected/reference-to-properties.additional.ts
tests/v3/expected/stripe.additional.ts

Fixes #693, #554
According to #693, I believe this is correct:
>According to the [OpenAPI spec](https://swagger.io/docs/specification/data-models/data-types/#any), when a schema is defined without a type it is the equivalent of:
>
>```
>      anyOf:
>        - type: string
>        - type: number
>        - type: integer
>        - type: boolean
>        - type: array
>          items: {}
>        - type: object
>```
>
>but openapi-typescript uses [`object` type as the default](https://github.com/drwpow/openapi-typescript/blob/main/src/types.ts#L102) and [generates](https://github.com/drwpow/openapi-typescript/blob/main/src/transform/schema.ts#L116-L121) `{ [key: string]: unknown }`. Instead it should generate just `unknown`.
This PR addresses that, fixing some bugs in the process. And …

Improve generated types for unknown schema objects

---

README.md

Added link to [openapi-typescript-fetch](https://www.npmjs.com/package/openapi-typescript-fetch) with sample usage. This library infers the response and error types from the generated code and adds a fetch implementation.

README: openapi-typescript-fetch

---

.gitignore
bin/cli.js
package-lock.json
package.json
src/index.ts
src/load.ts
src/transform/headers.ts
src/transform/index.ts
src/transform/operation.ts
src/transform/parameters.ts
src/transform/paths.ts
src/transform/request.ts
src/transform/responses.ts
src/transform/schema.ts
src/utils.ts
test/core/operation.test.js
test/core/parameters.test.js
test/core/paths.test.js
test/core/request.test.js
test/core/schema.test.js
test/opts/empty-definitions.test.js
test/opts/formatter.test.js
test/opts/raw-schema.test.js
test/opts/remote-schema.test.js
test/v2/index.test.js
test/v3/index.test.js
tsconfig.json

- Patches a [security issue](https://security.snyk.io/vuln/SNYK-JS-NODEFETCH-2342118) with `node-fetch`, but rather than update, switches to `undici`.
- Removes CJS build (mostly because of type errors)
- Fixes a type export error for an upcoming TS version (#847)

Remove CJS build, update deps, use undici

---

README.md

Adds flag info to README, updates README flags to more closely match `--help`

Add --export-type to README, flag cleanup

---

src/transform/paths.ts
test/bin/expected/paths-enum.ts

Closes #911
Pretty straight-forward. I was just about to use this functionality myself when I encountered the unreachable enum.
The `enum` was being generated, but simply wasn't exported.
This PR adds the `export`, and updates the associated spec output.

fix: export enum of operation paths

---

src/utils.ts
test/bin/expected/specs/manifold.ts
test/v2/expected/http.ts
test/v2/expected/manifold.immutable.ts
test/v2/expected/manifold.ts
test/v3/expected/github.additional.ts
test/v3/expected/github.exported-type.ts
test/v3/expected/github.immutable.ts
test/v3/expected/github.support-array-length.ts
test/v3/expected/github.ts

Complex `default` and `example` values were serialized in comments at `[Object object]`.
This PR attempts to recognize these values, and to serialize them in a more-useful way.
This PR depends on both https://github.com/drwpow/openapi-typescript/pull/909 and https://github.com/drwpow/openapi-typescript/pull/906

Fix serialize object

---

src/transform/schema.ts
src/utils.ts
test/core/schema.test.js

https://github.com/drwpow/openapi-typescript/issues/898
This PR allows arrays of types to be parsed properly, as per the 3.1 specification. 
- Adds recursive functionality to parse "arrays" of types
- Supports the "null" type 
- I tested this locally using my company's openapi spec at https://developers.arcadia.com/openapi.yaml. I feel  a little weird about including this in a test because openapi-typescript does not support OpenAPI 3.1 - **How should I add a test for this?**

Support Type Arrays for OpenAPI 3.1

---

.github/workflows/ci.yml
CONTRIBUTING.md
package.json
pnpm-lock.yaml
test/bin/cli.test.js
test/core/operation.test.js
test/core/parameters.test.js
test/core/paths.test.js
test/core/request.test.js
test/core/schema.test.js
test/opts/empty-definitions.test.js
test/opts/formatter.test.js
test/opts/raw-schema.test.js
test/opts/remote-schema.test.js
test/v2/index.test.js
test/v3/index.test.js

Mocha and Chai were very cool, but Vitest is cooler 😎 
(also, Vitest uses Chai under the hood, so this is more a Mocha replacement)
In case you haven’t used Vitest yet, it’s the best test runner in all of Node history. No, I’m no exaggerating.

use Vitest for test runner

---

README.md
bin/cli.js
package.json
pnpm-lock.yaml
test/cli.test.ts

- Adds `--version` flag that does the normal boring version thing
- Adds CLI tests

Add --version flag, add CLI tests

---

examples/digital-ocean-api.ts
examples/github-api.ts
examples/octokit-ghes-3.6-diff-to-api.ts
examples/stripe-api.ts
src/transform/schema-object.ts
src/types.ts
test/schema-object.test.ts

- Fixes #979 
- Fixes #981
Tests should pass

Fix nullable types, additionalProperties behavior

---

src/transform/operation-object.ts
src/transform/path-item-object.ts
test/paths-object.test.ts

Fixes the generation of parameters containing a `.` in the description. See https://github.com/drwpow/openapi-typescript/issues/985

Fix generation of parameters with a dot in the description

---

examples/octokit-ghes-3.6-diff-to-api.ts
examples/stripe-api.ts
src/index.ts
test/index.test.ts

Fix https://github.com/drwpow/openapi-typescript/issues/976 by checking if `OneOf` type is added to the schema. The fix uses the easiest path, but perhaps not the best for long term (if there are other type helpers added especially). Perhaps, the context should be aware if type helpers are required? (if it's not already the case and that I miss something).

Add type helpers only when used

---

src/load.ts

Undici returns headers in lowercase as it can be seen [here](https://github.com/nodejs/undici/blob/a3ce745b0c5d7c837ecae2359434ab4550a6e0ea/lib/core/util.js#L214). This PR updates the `content-type` check in order to use the lowercase version.

Use lowercase headers

---

bin/cli.js

Fixes https://github.com/drwpow/openapi-typescript/issues/925
The issue is that the original `outputDir` was being mutated, so each itteration would create more nested folders.
1. Create 2 directories holding 2 different OpenAPI contracts (e.g. `src/contracts/service1/openapi.yaml` and `src/contracts/service2/openapi.yaml`
2. Attempt to generate types to different target directory, e.g. `src/generated` via `openapi-typescript src/contracts/**/openapi.yaml --output ./src/generated/api/`
In the non-pathed version the command will fail, multiple invalid directories will be created.

Fix bug in generating multiple spec to folder

---

examples/digital-ocean-api.ts
examples/github-api.ts
examples/octokit-ghes-3.6-diff-to-api.ts
examples/stripe-api.ts
src/transform/index.ts
src/transform/webhooks-object.ts
src/types.ts
test/index.test.ts
test/webhooks-object.test.ts

Implements webhooks. I am usually verbose in my PR descriptions but here the change is quite straightforward. The specs define `webhooks` as being identical to `paths` (with the exception that it does not have actual paths), so I just copy-pasted the implementation for paths and removed the bit that relates to `pathParamsAsTypes`.
Fixes #994.
I don't know. There was a lot of changes in the test due to the inclusion of `export type webhooks = Record<string, never>;`,  but the only test that is actually relevant is the "GitHub (next)" snapshot, which is the only one with webhooks (the normal GitHub one has them as well but on a non-standard property, which is `x-webhooks`).
For the unit test I took inspiration from the paths' one. I hope it is sufficient.
I don't think there is anything to …

Implement Webhooks

---

src/index.ts
src/load.ts
src/types.ts
src/utils.ts
test/load.test.ts

When loading the schema, the `load` function used to only consider the Content-Type header when capitalized. However, the HTTP specification states that headers are to be treated as case-insensitive. HTTP/2 further enforces this by stating that all HTTP headers must be converted to lowercase when encoded. Therefore, many recent implementations move away from the conventional capitalization in favour of headers in lowercase, such as the Nest framework.
In issue #988, it is shown that loading the schema from a live server implemented in Nest fails when the endpoint does not include the desired extension.
This commit fixes the issue by replacing unidici's request by fetch. The request function returns headers as a record, where the keys are left exactly as the headers are received, meaning …

Use overridable fetch instead of unidici's request

---

src/transform/operation-object.ts
test/path-item-object.test.ts

OpenAPI allows to use HTTP ranges for response keys, see:
https://swagger.io/docs/specification/describing-responses/#status-codes
Before these changes, openapi-typescript would output invalid
TypeScript when processing schemas with HTTP ranges.
Are the test I added enough?

Fix response key for HTTP ranges

---

src/transform/schema-object.ts
test/schema-object.test.ts

Given the schema
```ts
const schema: SchemaObject = {
type: "object",
properties: { "constant": {"const": "a", "type": "string"} },
required: ["constant"],
};
```
the generator would build this
```
/** @constant */
constant: a;
```
which isn't valid typescript. I think the same issue was properly taken care of for enums in https://github.com/drwpow/openapi-typescript/blob/main/src/transform/schema-object.ts#L80, so I've used the same approach here.
I hope this should be pretty uncontroversial. Maybe the string cast should also be applied if no type is specified, but not sure about that. This would be the minimal fix for the API we're documenting.

Escape constant string in generated schema

---

src/transform/schema-object.ts
test/schema-object.test.ts

Fixes #1016
I took my best guess at what the test for this should look like based on the existing test suite. The new test does demonstrate the bug (fails in the same way as my real-world case, passes with the code change). But it feels a bit brittle to me, in that it's hardwiring a bunch of context and the source of the original bug was a mismatch between what was really in that context and what the code expected to be there.
Happy to revise this if you think the test isn't adequate.

Support fully-qualified refs as discriminator mapping values

---

examples/digital-ocean-api.ts
examples/github-api.ts
src/index.ts
src/transform/schema-object.ts
src/types.ts
src/utils.ts
test/index.test.ts
test/schema-object.test.ts

Resolves #657
Resolves the issue described in #657 and updates the unit tests. Should be a fairly safe change as it is just additive to the current code generation without breaking changes. This solution will only work for OpenAPI 3.1 as described by the comment here https://github.com/drwpow/openapi-typescript/issues/657#issuecomment-1399274607

feat: add with required utility to enforce properties of allOf

---

src/transform/schema-object.ts
test/schema-object.test.ts
test/utils.test.ts

Fixing https://github.com/drwpow/openapi-typescript/issues/1051 alongside the fact that `0` as a const value was evicted.
I wrote tests, they all pass now.
FYI, I wanted to make sure everything is working as expected, so I added tests for the `tsOneOf` util. IMHO, all the utils should be tested (but I did not have time to write these tests).

Fix `oneOf` number const

---

README.md

Adds [openapi-fetch](https://github.com/drwpow/openapi-fetch) to the README as an alternate to openapi-typescript-fetch.
Also removed the “Simple Example” approach because that’s actually a bad idea. It shouldn’t be recommended, even hypothetically. Automatically-inferred types are trivially-possible. And manually assigning generics is not only error-prone; it’s more work!
Of course, openapi-typescript-fetch is kept in the README as a possible solution. I created openapi-fetch because of mostly a difference in opinion in how the API should work which demanded a separate library.
While other contributions/suggestions are welcome (if anyone else also makes a fetch wrapper they are free to suggest it, and I will add it in the README if it works well!), I didn’t suggest either of the …

Add openapi-fetch to readme

---

bin/cli.js

Currently, if a url like `https://api-test.<website>/docs/json` is passed, then the regex creates a file with the `https://` prefix before it, and so it doesn't work. It creates a file like `https://api-test.<website>.ts`

Fix path generation

---

examples/github-api.ts
examples/octokit-ghes-3.6-diff-to-api.ts
package.json
pnpm-lock.yaml
src/transform/components-object.ts
test/components-object.test.ts

Adds the missing dependency `vite` and fixes #1052.
Vitest requires vite to run. See the [docs](https://vitest.dev/guide/#adding-vitest-to-your-project).
The fix is in [src/transform/components-object.ts](https://github.com/drwpow/openapi-typescript/compare/main...AplusKminus:pr/1052-optional-parameters?expand=1#diff-634b9bd5c5b9a703854a113903645247449a00a797280dcc09e15849f12fdf50), the rest is just test adjustments, updated snapshots and the added dependency.

Ensure not required parameters are created as optional properties

---

examples/digital-ocean-api.ts
examples/digital-ocean-api/resources/databases/models/database_cluster.yml
examples/digital-ocean-api/resources/databases/responses/database_cluster.yml
examples/github-api.ts
examples/octokit-ghes-3.6-diff-to-api.ts
examples/stripe-api.ts
examples/stripe-api.yaml
src/utils.ts
test/schema-object.test.ts
test/utils.test.ts

If a union has multiple members that are the same, then we should de-duplicate them.
https://github.com/drwpow/openapi-typescript/pull/1049#discussion_r1159448414

De-duplicate unions.

---

src/utils.ts
test/utils.test.ts

Fixes #915, added some regression tests for `parseRef`
Minimal repro on that issue now generates as:
```ts
export interface components {
schemas: {
someschema: components["schemas"]["\""];
"\"": string;
};
responses: never;
parameters: never;
requestBodies: never;
headers: never;
pathItems: never;
}
```
as expected, and the original example also generates correctly:
```ts
export interface components {
schemas: {
IUserWithId: components["schemas"]["Partial<Pick<IUser,\"id\">>"] | string;
"Partial<Pick<IUser,\"id\">>": {
id?: number;
};
IUserWithName: {
name: string;
};
}
}
```
Tests

Don't attempt to double-escape double quotes

---

src/transform/schema-object.ts
test/schema-object.test.ts

Sorry, when solving the problem of generating tuples type before, the unit test assertion was written incorrectly, but now it is correct
test
tuples type schema
{ type: "array", items: [{ type: "string" },{"type": "number"}],minItems:2,maxItems:2 }
The corresponding data should be:
[string, number]

fix: tuples type generation bug, and unit test bug.

---

bin/cli.js

I couldn't find an issue. But here is my error:
```
Error: EISDIR: illegal operation on a directory, open '/Users/don.denton/GitProjects/my-project/server-sdk/'
at Object.openSync (node:fs:601:3)
at Object.writeFileSync (node:fs:2249:35)
at generateSchema (file:///Users/don.denton/.npm/_npx/f0a53e56ae94fd64/node_modules/openapi-typescript/bin/cli.js:136:8)
at async file:///Users/don.denton/.npm/_npx/f0a53e56ae94fd64/node_modules/openapi-typescript/bin/cli.js:209:7
at async Promise.all (index 0)
at async main (file:///Users/don.denton/.npm/_npx/f0a53e56ae94fd64/node_modules/openapi-typescript/bin/cli.js:199:3) {
errno: -21,
syscall: 'open',
code: 'EISDIR',
path: '/Users/don.denton/GitProjects/my-project/server-sdk/'
}
```
When I log …

Fix incorrect check for protocol

---

CONTRIBUTING.md
src/transform/path-item-object.ts
src/types.ts
test/index.test.ts

Fixes #1065. This was a dumb bug where we just didn’t do a complete parameter lookup if it had an `operationId` 🤦. Was as easy as moving a couple lines of code above the `if()` statement.
Captured in tests; tests should pass.

Fix missing parameters in operation object

---

examples/digital-ocean-api.ts
examples/github-api.ts
examples/octokit-ghes-3.6-diff-to-api.ts
examples/stripe-api.ts
examples/stripe-api.yaml
src/transform/operation-object.ts
test/index.test.ts
test/paths-object.test.ts

If all query parameters are optional we should use `query?: { ... }` instead of `query: { ... }`. Or when we use libs like `openapi-fetch` we have to always write an empty `query: {}` on the request like:
```ts
const res = await client.get('/do/{id}', {
params: {
query: {},
path: {
id: 123,
},
},
})
```
We expect to use code like this:
```ts
const res = await client.get('/do/{id}', {
params: {
path: {
id: 123,
},
},
})
```

make query optional if all params are optional

---

docs/src/components/Header/Search.tsx
docs/src/consts.ts

Moves Algolia settings to env vars. These aren’t really secret, but are easier to manage in Cloudflare Pages.

Add Algolia env vars

---

docs/src/components/Header/Search.tsx
docs/src/components/LeftSidebar/LeftSidebar.astro
docs/src/layouts/MainLayout.astro
packages/openapi-fetch/CHANGELOG.md
packages/openapi-fetch/src/index.test.ts
packages/openapi-fetch/src/index.ts
packages/openapi-fetch/test/v1.yaml

Adds search index for new docs site. No openapi-typescript changes.
Also updates openapi-fetch, but only mirrors changes from https://github.com/drwpow/openapi-fetch. Still not deploying that package from here yet (not until docs site is ready).

Add Algolia search script, update openapi-fetch

---

docs/src/content/docs/cli.md
packages/openapi-typescript/README.md
packages/openapi-typescript/bin/cli.js
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/transform/components-object.ts
packages/openapi-typescript/src/transform/header-object.ts
packages/openapi-typescript/src/transform/operation-object.ts
packages/openapi-typescript/src/transform/paths-object.ts
packages/openapi-typescript/src/transform/request-body-object.ts
packages/openapi-typescript/src/transform/response-object.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/src/transform/webhooks-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/src/utils.ts
packages/openapi-typescript/test/components-object.test.ts
packages/openapi-typescript/test/header-object.test.ts
packages/openapi-typescript/test/load.test.ts
packages/openapi-typescript/test/path-item-object.test.ts
packages/openapi-typescript/test/paths-object.test.ts
packages/openapi-typescript/test/request-body-object.test.ts
packages/openapi-typescript/test/schema-object.test.ts
packages/openapi-typescript/test/webhooks-object.test.ts

Often time we want to exclude deprecated fields completely from generated types so we can spot deprecated fields asap. 
Unfortunately, TS doesn't have a such option: https://github.com/microsoft/TypeScript/issues/49433
The code editor shows deprecated fields with scratched out, which is nice but not enough.
For example, you created a new version of SDK, then you wish TS would complain about use of deprecated fields asap but it doesn't. 
It should be straight forward to review but I'm not sure if I should add this option on every single `getEntries` usages.

feat: introduce excludeDeprecated option

---

.changeset/wise-badgers-kick.md
packages/openapi-typescript/src/transform/paths-object.ts
packages/openapi-typescript/test/index.test.ts

The existing code for `--path-params-as-types` assumes path parameters are defined on the PathItemObject:
```javascript
{
openapi: "3.1",
info: { title: "Test", version: "1.0" },
paths: {
"/user/{user_id}": {
parameters: [{ name: "user_id", in: "path" }],
},
},
}
```
But its valid to define them on the OperationObject:
```javascript
{
openapi: "3.1",
info: { title: "Test", version: "1.0" },
paths: {
"/user/{user_id}": {
get: {
parameters: [{ name: "user_id", in: "path" }],
},
put: {
parameters: [{ name: "user_id", in: "path" }],
}
},
},
}
```
[FastAPI](https://github.com/tiangolo/fastapi) does it this way.
This is both my first openapi-typescript PR _and_ my first typescript PR. Don't hold back.

fix: support nested path parameters in --path-params-as-types

---

.changeset/config.json
docs/package.json
package.json
pnpm-lock.yaml

Testing out the release flow was a good idea, since it tried to publish the docs to npm. This fixes that.

Hide docs from npm publish

---

.github/workflows/release.yml
package.json
packages/openapi-typescript/CHANGELOG.md

Adds a `pnpm i` to the versioning script, and lets changesets publish to npm. Hopefully this is it! 🤞

Update version script

---

.changeset/sixty-bobcats-jam.md
docs/src/content/docs/openapi-fetch/index.md
packages/openapi-fetch/README.md
packages/openapi-fetch/src/index.test.ts
packages/openapi-fetch/src/index.ts
packages/openapi-fetch/test/v1.d.ts
packages/openapi-fetch/test/v1.yaml

`response.default` was simply ignored. Instead, treat it as an error.
While some may disagree—technically it can be either—in my observation this is how most people use it since its purpose is handling **unexpected** HTTP codes (aka exceptions aka errors).
At any rate, interpreting `default` as _something_ rather than ignoring it is an improvement.
Tests added; CI should pass

fix(openapi-fetch): treat default response as error

---

docs/src/consts.ts

Fixes site description, as used in [Slack unfurls](https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254).
Ensure updated site description is appropriate for Slack unfurls.

chore(docs): Update site description

---

packages/openapi-fetch/package.json

Fixes publish error. After moving from https://github.com/drwpow/openapi-fetch, this version was accidentally out-of-sync with npm. This is a one-time change due to migrating.

Fix openapi-fetch version

---

.changeset/gold-berries-kick.md
packages/openapi-typescript/src/utils.ts
packages/openapi-typescript/test/utils.bench.ts
packages/openapi-typescript/test/utils.test.ts

Fixes #1093. Supercedes #1097.
Tests should pass

Fix js-yaml $ref

---

.changeset/selfish-ears-hope.md
packages/openapi-typescript/src/transform/paths-object.ts
packages/openapi-typescript/test/paths-object.test.ts

It fixes using `--path-as-params-types` option for paths that doesn't contain a param (like `/api/user`). In that case, using the option causes generating path name as `[path: '/api/user']` and produces compiler error `An index signature parameter type cannot be a literal type or generic type. Consider using a mapped object type instead.
`
It fixes [this fix](https://github.com/drwpow/openapi-typescript/pull/1130). The `pathParams` variable  is already non-empty variable, but can have empty size.

fix: Avoid index signature error for paths with empty params

---

.changeset/five-eels-call.md
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/schema-object.test.ts
packages/openapi-typescript/test/utils.test.ts

Fix #1162. Also added some additional object key escaping tests.
Nothing special

Fix property escaping for discriminators

---

packages/openapi-fetch/package.json

Also to fix #1102, but unlike #1103, this PR reuses `esbuild` instead of adding a new dependency.
Just change the `--format` flag to bundle cjs.
Ref https://esbuild.github.io/api/#format-commonjs
Is this type of bundling acceptable?
N/A
If your project/package is being blocked by the lack of cjs distribution for openapi-fetch, you can temporarily try using [`@kecrily/openapi-fetch`](https://www.npmjs.com/package/@kecrily/openapi-fetch) based on this PR before this PR is merged.

build(openapi-fetch): bundle commonjs

---

docs/src/content/docs/openapi-fetch/api.md
docs/src/content/docs/openapi-fetch/examples.md
packages/openapi-fetch/README.md

Docs-only change: Adds React Query example for openapi-fetch.

Add React Query example to docs for openapi-fetch

---

docs/src/content/docs/openapi-fetch/examples.md

Docs-only change; adds Vanilla JS caching example for openapi-fetch

Add Vanilla JS caching example

---

.changeset/four-carpets-push.md
packages/openapi-fetch/README.md
packages/openapi-fetch/src/index.test.ts
packages/openapi-fetch/src/index.ts

- add a global `querySerializer` option to `createClient()`
- add tests for the global serializer, and to ensure serializers provided to individual fetch methods override the global serializer
- update readme
Resolves #1182
I don't know how to correctly type the added global `querySerializer` option - set it to `QuerySerializer<unknown>`.

feat(openapi-fetch): add global `querySerializer` option (#1182)

---

.changeset/spotty-eggs-tickle.md
package.json

Fixes #1185. The build triggered by the autorelease is different than the `build` script dictated by each package. While `openapi-typescript` was unaffected, `openapi-fetch` had missing files in the latest release.
Will have to release to check 🤞

Fix monorepo release build

---

.changeset/nasty-windows-chew.md
docs/src/content/docs/node.md
packages/openapi-typescript/README.md

Add example `transform` callback for file uploads, where the `multipart/form-data` has a field that should be typed as `Blob`.
Update the README with additional example for what I think is a common use-case.
Maybe this is extraneous? Dunno. I see the `stripe` API in `examples` has some schemas that should have this transformation done.
Should this transformation be the default behaviour?
- ~~[ ] Unit tests updated~~
- ~~[ ] `examples/` directory updated (only applicable for openapi-typescript)~~

Update README.md with `transform` example for `Blob`

---

.changeset/quick-parrots-worry.md
docs/src/content/docs/node.md

Update docs with examples for using the Node.js API in a project with a browser build target. 
I'm not sure if this deserved to be in the docs as it's only tangential to `openapi-typescript`, and I imagine most devs know how to set this up already. 
I, however, didn't know, and it took me an hour of going down stack-overflow garden paths before discovering `ts-node --esm`, so I figured I'd propose the changes.
- ~~[ ] Unit tests updated~~
- ~~[ ] `examples/` directory updated (only applicable for openapi-typescript)~~

docs(openapi-ts): add docs for using Node.js API in web projects

---

.changeset/config.json
.changeset/nasty-windows-chew.md
.changeset/quick-parrots-worry.md

Changelogs don’t need to be generated for the documentation (version doesn’t need to be bumped)
N/A
N/A

Ignore docs from changesets

---

.changeset/fresh-dancers-joke.md
packages/openapi-typescript/src/load.ts
packages/openapi-typescript/test/index.test.ts

Fix mutating $refs in Node.js API

---

.changeset/tasty-knives-matter.md
packages/openapi-typescript/src/utils.ts
packages/openapi-typescript/test/schema-object.test.ts

Fixes #1019. At `oneOf` length of > 5, fall back to TS unions rather than the complex custom `OneOf<>` (XOR) comparison.
This is tough because it’s hard to predict just _how complex_ some types would be, so there’s not a correct number. But hopefully most people see an invisible improvement in types, and if we see new issues come in we’ll adjust based on feedback.
See #1019 for context.

Fix complex oneOf

---

.github/workflows/ci.yml
.github/workflows/release.yml

Node 18.x is used in GitHub Actions when 20.x would be faster.
N/A
N/A

Use Node 20.x in GitHub Actions

---

packages/openapi-typescript/test/cli.test.ts

Not due to any perf regressions; this is just necessary for the macOS runner in GitHub Actions to complete the DigitalOcean snapshot test. Fortunately, bumping up a test timeout doesn’t slow it down; it merely _allows_ it to be slow when needed.
N/A
N/A

Bump up test timeout

---

packages/openapi-typescript/test/load.test.ts
packages/openapi-typescript/test/utils.test.ts

Chore; tests `parseRef()` without changing any functionality.

Add add’l parseRef tests

---

.changeset/gold-bugs-chew.md
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/load.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/fixtures/_schema-test-partial.yaml
packages/openapi-typescript/test/fixtures/remote-ref-test.yaml
packages/openapi-typescript/test/index.test.ts

Fixes #1131. There are likely some other bugs with deeply-nested remote schemas, but this fixes at least one.
The reason was in our `getHint()` logic that traverses the nodePath, it wasn’t keeping track of remote filenames, which is necessary for certain inferences (the hints are necessary because partial schemas could be _anything_ and still be valid—the only way to know is by tracing from the root). There’s probably a better solution than this, but this will do for now.

Fix remote schema maps

---

.changeset/shy-turtles-taste.md
packages/openapi-typescript/examples/github-api.ts
packages/openapi-typescript/examples/octokit-ghes-3.6-diff-to-api.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/schema-object.test.ts

Related to: #1197
JSON schemas like:
```json
{
"properties": {
"petType": {
"type": [
"null",
"string"
],
"enum": [
"foo", "bar"
]
}
}
}
```
..results into:
```ts
{
petType: "foo" | "bar" | ""
}
```
...which seems to add an unexpected empty string to the union. See the example in [this JSON schema validator](https://www.jsonschemavalidator.net/s/4oHwGoE7).
With this PR the empty `""` is removed from the union:
```ts
{
petType: "foo" | "bar"
}
```
Happy to review the PR based on your suggestions!
In case type contains `null` but then `null` is not listed as enum:
```json
{
"properties": {
"petType": {
"type": [
"null",
"string"
],
"enum": [
"foo", "bar"
]
}
}
}
```
..I understand the result should not contain `null`. See [this online validator test …

fix: empty strings in enums when type [string, null]

---

.changeset/stale-beers-sleep.md
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/examples/github-api.ts
packages/openapi-typescript/examples/octokit-ghes-3.6-diff-to-api.ts
packages/openapi-typescript/examples/stripe-api.ts
packages/openapi-typescript/src/utils.ts
packages/openapi-typescript/test/schema-object.test.ts

Draft: waiting for #1231 to be merged
Before:
```
/** A title */
fooBar: (string)[];
```
After:
```
/** A title */
fooBar: string[];
```

Remove unnecessary array parenthesis

---

.changeset/red-fans-act.md
packages/openapi-fetch/package.json
packages/openapi-fetch/src/index.test.ts
packages/openapi-fetch/src/index.ts
packages/openapi-fetch/test/v1.d.ts
packages/openapi-fetch/test/v1.yaml
pnpm-lock.yaml

Fixes #1230. Adds testing & support for `params.header`.

Fix params.header missing in request

---

.changeset/witty-ears-change.md
docs/src/content/docs/openapi-fetch/api.md
docs/src/content/docs/openapi-fetch/examples.md
docs/src/content/docs/openapi-fetch/index.md
packages/openapi-fetch/README.md
packages/openapi-fetch/src/index.test.ts
packages/openapi-fetch/src/index.ts

Renames all methods to uppercase, following discussion of #1218.
Particularly pertinent is SvelteKit’s prior art of also using uppercase methods ([discussion](https://github.com/sveltejs/kit/discussions/5359)). It’s an exact overlap, and I think this discussion alone makes more than enough reason to make the change (plus, aligning with SvelteKit is never a bad thing 🙂).

Rename all methods to UPPERCASE

---

.changeset/stupid-pens-bow.md
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/examples/digital-ocean-api/resources/kubernetes/models/node_pool.yml
packages/openapi-typescript/examples/stripe-api.ts
packages/openapi-typescript/examples/stripe-api.yaml
packages/openapi-typescript/package.json
packages/openapi-typescript/scripts/download-schemas.ts
packages/openapi-typescript/scripts/schemas.ts
packages/openapi-typescript/scripts/update-examples.ts
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/load.ts
packages/openapi-typescript/src/transform/path-item-object.ts
packages/openapi-typescript/src/transform/paths-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/fixtures/_path-object-refs-paths.yaml
packages/openapi-typescript/test/fixtures/path-object-refs.yaml
packages/openapi-typescript/test/index.test.ts
packages/openapi-typescript/test/path-item-object.test.ts

Fixes #1107. Also squashes quite a few remote schema bugs in the process, too 🎉 

Fix remote path item object $refs

---

docs/src/content/docs/openapi-fetch/examples.md
docs/src/content/docs/openapi-fetch/index.md
packages/openapi-fetch/README.md
packages/openapi-fetch/package.json

The sad day has come `openapi-fetch` has reached 2 kb 😱. Rest assured we will work diligently to remove all the added bloat in the future. But until then, fix the inconsistent size reporting.
Docs-only change.

Fix openapi-fetch size

---

.changeset/stale-shoes-sell.md
packages/openapi-fetch/src/index.test.ts
packages/openapi-fetch/src/index.ts
packages/openapi-fetch/test/v1.d.ts
packages/openapi-fetch/test/v1.yaml
packages/openapi-typescript/test/operation-object.test.ts

Adds support for `2XX`, `4XX`, and `5XX` responses in schema, which is [supported by the spec](https://spec.openapis.org/oas/v3.1.0#x4-8-16-2-patterned-fields).
Funny enough, I have never used this or seen this; just happened to skim over that definition and saw it was allowed. In `openapi-typescript` we just skip right over this and don’t need to handle it. But `openapi-fetch` needed to add this for proper support.

Fix 2XX, 4XX, 5XX responses

---

.github/pull_request_template.md
README.md
docs/CONTRIBUTING.md
docs/README.md

- Adds guides / READMEs on contributing to documentation
- Expands READMEs to be a little more helpful.
Docs-only change.

Expand README, add docs contributing guide

---

docs/src/content/docs/openapi-fetch/index.md
packages/openapi-fetch/README.md

Wow I’m really bad at find-and-replace, huh?

Fix openapi-fetch reported size (2)

---

.changeset/long-poems-study.md
packages/openapi-fetch/package.json
packages/openapi-typescript/.npmignore
packages/openapi-typescript/package.json
packages/openapi-typescript/test/cjs.test.ts
pnpm-lock.yaml

Addresses #888. Exports a CJS bundle for `openapi-typescript`. Does so via [package.json `exports`](https://nodejs.org/api/packages.html#main-entry-point-export) so it requires a fairly-modern version of Node (but all current supported versions do).
Bundles via esbuild to gloss over complexities of CJS vs ESM deep imports for dependencies. Since all the dependencies are tiny, the bundle isn’t too bad
Tests should pass

Export CJS bundle

---

docs/src/content/docs/advanced.md

Docs-only change; updates the testing example to be a little bit better shape (sending headers isn’t always possible / probably isn’t realistic for most setups)
Docs-only change, but Cloudflare Pages should deploy

Update testing example

---

.changeset/new-rats-yawn.md
packages/openapi-typescript/src/utils.ts
packages/openapi-typescript/test/schema-object.test.ts

This PR attempts to fix #1224 while minimizing other impact.
The unit test gives a clear example of the scenario in which the behaviour is currently not as expected. The code change is required to make the unit test pass.

Stop trimming whitespace other than linebreaks in string values

---

.changeset/swift-badgers-notice.md
packages/openapi-typescript/src/load.ts
packages/openapi-typescript/test/fixtures/anchor-with-ref-test-2.yaml
packages/openapi-typescript/test/fixtures/anchor-with-ref-test.yaml
packages/openapi-typescript/test/index.test.ts

Fixes #1276 
I'm unsure if this is a complete fix. It fixes my case, but there might be others that I overlooked.

Fix externalizing external refs

---

.eslintrc.cjs
docs/CONTRIBUTING.md
package.json
packages/openapi-fetch/CONTRIBUTING.md
packages/openapi-fetch/package.json
packages/openapi-fetch/src/index.test.ts
packages/openapi-fetch/src/index.ts
packages/openapi-typescript/CONTRIBUTING.md
packages/openapi-typescript/package.json
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/load.ts
packages/openapi-typescript/src/transform/components-object.ts
packages/openapi-typescript/src/transform/operation-object.ts
packages/openapi-typescript/src/transform/parameter-object-array.ts
packages/openapi-typescript/src/transform/paths-object.ts
packages/openapi-typescript/src/transform/request-body-object.ts
packages/openapi-typescript/src/transform/response-object.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/src/transform/webhooks-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/src/utils.ts
packages/openapi-typescript/test/cjs.test.ts
packages/openapi-typescript/test/invalid.test.ts
packages/openapi-typescript/test/utils.test.ts
pnpm-lock.yaml

Updates Prettier to 3.0, updates `@typescript-eslint` to latest version. Also some minor CONTRIBUTING.md fixes.
CI should pass
N/A

Update Prettier, linting deps

---

.changeset/cold-pets-sit.md
packages/openapi-fetch/src/index.test.ts
packages/openapi-fetch/src/index.ts
packages/openapi-fetch/test/v1.d.ts
packages/openapi-fetch/test/v1.yaml

Improves #1124 by adding better inference to “impossible” body types. But I think the real fix will come in #1280 which fixes the underlying typing for responses.
CI should pass.
N/A

Improve impossible body typing

---

.changeset/nice-avocados-bake.md
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/schema-object.test.ts

Fix #1277, where a `"type": "object"` SchemaObject has a `oneOf` property but no properties of its own.
CI should pass

Fix oneOf + empty object parent case

---

.changeset/gold-gorillas-kiss.md
packages/openapi-typescript/bin/cli.js

Fixes #1091
Uses of `URL` have been replaced by their `path` variants. This makes more sense because we're handling actual file paths here. This fixes several bugs, including the reporting one, but also for example exporting to absolute paths.

Refactor CLI path handling, fixing several bugs

---

.changeset/mighty-ligers-cheat.md
packages/openapi-fetch/test/v1.d.ts
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/examples/octokit-ghes-3.6-diff-to-api.ts
packages/openapi-typescript/src/transform/request-body-object.ts
packages/openapi-typescript/src/transform/response-object.ts
packages/openapi-typescript/test/components-object.test.ts
packages/openapi-typescript/test/index.test.ts
packages/openapi-typescript/test/request-body-object.test.ts
packages/openapi-typescript/test/response-object.test.ts
packages/openapi-typescript/test/webhooks-object.test.ts

Fixes #1109 and #1174
Nothing special

Fix empty request / response bodies

---

.changeset/ninety-tips-sip.md
docs/src/content/docs/advanced.md
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/examples/stripe-api.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/index.test.ts
packages/openapi-typescript/test/schema-object.test.ts

Fixes #1267 and #1018 
A slightly tricky part about this is that we need to account for objects with not all properties required. In that case, we still need to add undefined to the index signature to avoid TypeScript errors

Avoid adding undefined to the index signature for additionalProperties

---

.changeset/tiny-waves-help.md
package.json
packages/openapi-fetch/package.json
packages/openapi-fetch/src/index.ts
packages/openapi-typescript-helpers/CHANGELOG.md
packages/openapi-typescript-helpers/LICENSE
packages/openapi-typescript-helpers/README.md
packages/openapi-typescript-helpers/index.d.ts
packages/openapi-typescript-helpers/index.js
packages/openapi-typescript-helpers/package.json
packages/openapi-typescript-helpers/tsconfig.json
packages/openapi-typescript/tsconfig.json
pnpm-lock.yaml
tsconfig.json

Adds `openapi-typescript-helpers` package, as suggested in https://github.com/drwpow/openapi-typescript/discussions/1259. Still a bit of a WIP, but will be nice just being able to have types for anything that comes up. That way we have it
- Tests should pass (`openapi-fetch` especially)

Add openapi-typescript-helpers package

---

docs/package.json
docs/src/content/docs/advanced.md
docs/src/content/docs/introduction.md
packages/openapi-typescript/README.md
packages/openapi-typescript/package.json
pnpm-lock.yaml

Adds a note about `noUncheckedIndexedAccess` in the setup section, and links to the TS docs in the extended passage
Docs-only change; no code changes

Minor docs change

---

docs/src/components/RightSidebar/TableOfContents.tsx
docs/src/content/docs/about.md
docs/src/content/docs/openapi-fetch/about.md
docs/src/content/docs/openapi-fetch/api.md
docs/src/layouts/MainLayout.astro
docs/src/pages/index.astro
packages/openapi-typescript/package.json

Fixes a couple minor docs mistakes.
Docs-only change; no code changes

Minor docs updates

---

docs/src/content/docs/openapi-fetch/examples.md

Tiny update; just splits apart 2 codeblocks that shouldn’t have been combined.
Docs-only change; no code changes

Split apart 2 code snippets in docs

---

.changeset/gentle-socks-wink.md
.changeset/weak-games-exercise.md
packages/openapi-fetch/src/index.test.ts
packages/openapi-fetch/src/index.ts

Fixes #1298. Allows you to pass in `null` to headers to unset them (applicable to default headers either in the library or set with `createClient()`.
- Tests added; tests should pass

Allow unsetting default headers

---

.changeset/config.json
.changeset/kind-ladybugs-kneel.md
.changeset/sour-ants-walk.md
docs/public/robots.txt
docs/src/content/docs/advanced.md
packages/openapi-fetch/examples/nextjs/lib/api/v1.d.ts
packages/openapi-fetch/examples/react-query/src/lib/api/v1.d.ts
packages/openapi-fetch/examples/sveltekit/src/lib/api/v1.d.ts
packages/openapi-fetch/test/v1.d.ts
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/examples/octokit-ghes-3.6-diff-to-api.ts
packages/openapi-typescript/examples/stripe-api.ts
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/load.ts
packages/openapi-typescript/src/transform/components-object.ts
packages/openapi-typescript/src/transform/index.ts
packages/openapi-typescript/src/transform/schema-object-map.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/fixtures/_jsonschema-remote-obj.yaml
packages/openapi-typescript/test/fixtures/jsonschema-defs.yaml
packages/openapi-typescript/test/index.test.ts
packages/openapi-typescript/test/schema-object.test.ts
packages/openapi-typescript/test/yaml.test.ts

Fixes #1261 and adds support for JSONSchema `$defs` that can be defined on any object type or the root schema itself
⚠️ **Caveat**
Although in JSONSchema, `$defs` can be defined anywhere, unfortunately TypeScript doesn’t allow you to define keys on anything other than an `object`. For example, if you tried putting `$defs` on a `string`, how would you access them? Keep in mind that only object types (and the root schema itself) will keep their `$defs`.
- Tests added; tests should pass

Support JSONSchema $defs

---

.changeset/curly-mice-call.md
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/src/utils.ts
packages/openapi-typescript/test/schema-object.test.ts

Parenthesise readonly types.
Closes https://github.com/drwpow/openapi-typescript/issues/1319
Verify the changes to `parenthesise` continue wrap to the expected types.

fix: Wrap nested readonly members

---

.changeset/early-feet-report.md
packages/openapi-typescript-helpers/index.d.ts
packages/openapi-typescript-helpers/tsconfig.json

Fixes #1322. Caused by #1300, there was a type error that wasn’t being typechecked properly.
- Tests should pass

Fix missing type bug

---

.changeset/early-feet-report.md
packages/openapi-fetch/CHANGELOG.md
packages/openapi-fetch/examples/nextjs/package.json
packages/openapi-fetch/examples/react-query/package.json
packages/openapi-fetch/examples/sveltekit/package.json
packages/openapi-fetch/package.json
packages/openapi-typescript-helpers/CHANGELOG.md
packages/openapi-typescript-helpers/package.json
pnpm-lock.yaml

Fixes bug in `npx changeset version` caused by something weird with the `openapi-fetch/examples` folder. Probably a bug within Changesets, but either way should just be a quick manual fix.
This prepares `openapi-fetch@0.7.5` and `openapi-typescript-helpers@0.0.2` for release
N/A
N/A

openapi-fetch@0.7.5

---

packages/openapi-typescript/README.md

Fixed broken link to advanced.md in README
-

Fix broken URL in openapi-typescript/README

---

.changeset/four-ravens-shop.md
packages/openapi-fetch/CHANGELOG.md
packages/openapi-fetch/package.json
packages/openapi-typescript/CHANGELOG.md
packages/openapi-typescript/package.json
pnpm-lock.yaml

Release `openapi-typescript@6.5.5` and `openapi-fetch@0.7.6`.

openapi-typescript@6.5.5

---

packages/openapi-fetch/CONTRIBUTING.md
packages/openapi-typescript/CONTRIBUTING.md

Docs-only change; fixes a few typos and broken links in the contributing guides. Shortens some other language
N/A
N/A

Fix contributing typos

---

.changeset/friendly-numbers-tease.md
docs/src/content/docs/advanced.md
packages/openapi-typescript/examples/stripe-api.ts
packages/openapi-typescript/examples/stripe-api.yaml
packages/openapi-typescript/src/load.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/index.test.ts
packages/openapi-typescript/test/schema-object.test.ts

Fixes an issue where `propertyName` wasn’t automatically generated for `discriminators` (mappings are not required; they only are needed to override the automatic inference).
Related to #1158 and #1116
- Tests added; tests should pass.

Fix discriminator propertyName inference

---

.changeset/nice-sheep-juggle.md
.gitignore
packages/openapi-typescript/bin/cli.js
packages/openapi-typescript/test/cli.test.ts
packages/openapi-typescript/test/fixtures/cli-outputs/file-a.yaml
packages/openapi-typescript/test/fixtures/cli-outputs/file-b.yaml
packages/openapi-typescript/test/fixtures/cli-outputs/nested/deep/file-e.yaml
packages/openapi-typescript/test/fixtures/cli-outputs/nested/file-c.yaml
packages/openapi-typescript/test/fixtures/cli-outputs/nested/file-d.yaml

Fixes #1337 
Mirror the directory structure of input files if output is a directory. This prevents overwriting the same file again and again if there are multiple input files.

mirror directory structure if output is a directory

---

.changeset/brown-trainers-wink.md
packages/openapi-typescript/package.json
packages/openapi-typescript/src/load.ts

Fixes #1347. Simplifies YAML vs JSON parsing by simply checking if the file starts with `{`.
- All tests should pass

Improve YAML vs JSON parsing

---

packages/openapi-fetch/src/index.ts

This PR aims to fix a bug where the library would read the response's body before cloning it, which would result in the cloned response having an empty body after being cloned (at least in Bun).
This is a pretty minor fix, so I don't think there's any specific things to keep in mind when reviewing the changes.

Prevent using request body before cloning it

---

.changeset/honest-yaks-smell.md
.changeset/silent-carpets-grab.md
packages/openapi-fetch/src/index.test.ts
packages/openapi-fetch/src/index.ts
packages/openapi-typescript-helpers/index.d.ts

Fixes the elusive/annoying #1127. Now, rather than `.GET('/url', {})` being required, you can just write `.GET('/url')`. Minor QoL improvement, but very important fix!

Fix empty object required 2nd param

---

.changeset/chilled-news-design.md
docs/src/content/docs/advanced.md
packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/lib/ts.test.ts

This MR adds support for `x-enum-varnames` and `x-enum-descriptions` fields.
`x-enum-varnames` is used to set enum members names.
`x-enum-descriptions` is used to add comments for enum members.
Both fields are optional and affect generated code only if they are present in the schema.
There are no specific requirements.
The feature is similar to:
- https://openapi-generator.tech/docs/templating/#all-generators-core
- https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/custom-enums.md

Add support for x-enum-varnames and x-enum-descriptions

---

.changeset/chilled-news-design.md
packages/openapi-typescript/CHANGELOG.md

Manually adds a changeset into the changelog, so CI doesn’t try and automatically release `v7` on its own.
This is just an internal chore and doesn’t affect any runtime code.
N/A

Update changelog for v7

---

.changeset/chilly-cheetahs-attack.md
docs/src/content/docs/openapi-fetch/api.md
packages/openapi-fetch/src/index.ts
packages/openapi-fetch/test/index.test.ts
packages/openapi-fetch/test/v1.d.ts
packages/openapi-fetch/test/v1.yaml
packages/openapi-fetch/test/v7-beta.d.ts
packages/openapi-fetch/test/v7-beta.test.ts

Fixes #1331. Introduces a ⚠️ **Breaking Change** that changes the default behavior of `querySerializer` to explode query params by default (which now follows the expected behavior from the OpenAPI specification; it didn’t before).
- Tests were added to track behavior

Explode query params by default

---

.github/ISSUE_TEMPLATE/bug-report-fetch.md
.github/ISSUE_TEMPLATE/bug-report-ts.md
.github/ISSUE_TEMPLATE/feature-request-fetch.md
.github/ISSUE_TEMPLATE/feature-request-ts.md
packages/openapi-fetch/README.md
packages/openapi-typescript/README.md

Fixes documentation links as mentioned in #1358 
1. Double check that I didn't put the `openapi-fetch` links in the `openapi-typescript` templates
2. Notify of any additional links that are dead. I tried clicking through most of them, but I easily could have missed them.

fixes links in READMEs and issue templates

---

.changeset/witty-sheep-mix.md
packages/openapi-fetch/src/index.ts
packages/openapi-fetch/test/index.test.ts
packages/openapi-fetch/test/v7-beta.test.ts

Fixes #1403 by skipping empty arrays and objects in `querySerializer`
- Tests added

Fix behavior for empty arrays and objects in default querySerializer

---

docs/src/content/docs/advanced.md

This adds a new sections to the docs about combining `openapi-typescript` with MSW with `openapi-msw`, as we have discussed in this discussion: https://github.com/drwpow/openapi-typescript/discussions/1372#discussioncomment-7373824

docs: add section about openapi-msw

---

docs/src/content/docs/node.md
packages/openapi-typescript/src/transform/components-object.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/node-api.test.ts
packages/openapi-typescript/test/transform/components-object.test.ts
packages/openapi-typescript/test/transform/request-body-object.test.ts

This adds the possibility of appending a questionToken to a property using the transform function. Fixes #1411 
I am not 100% confident I covered all use cases of the transform function. Keep in mind that with the limited knowledge of this library, I might have missed some things.

Add questionToken option to transform

---

.github/workflows/ci.yml

CI-only change: Add Node 21.x to CI to test upcoming compatibility for when 22.x gets a stable release.
Will keep `macos` and `windows` locked to 20.x because those runners are expensive, and GitHub doesn’t queue those up too many (tried to expand the matrix to include these, but it just blocked the CI pipeline for a half hour)
- CI should pass (🤞)
N/A

Add Node 21 to CI

---

packages/openapi-typescript/src/transform/index.ts
packages/openapi-typescript/src/transform/operation-object.ts
packages/openapi-typescript/src/transform/parameters-array.ts
packages/openapi-typescript/src/transform/path-item-object.ts
packages/openapi-typescript/src/transform/paths-object.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/cli.test.ts
packages/openapi-typescript/test/transform/components-object.test.ts
packages/openapi-typescript/test/transform/schema-object/array.test.ts
packages/openapi-typescript/test/transform/schema-object/object.test.ts

Fixes `--immutable` types in v7 (beta) ([comment](https://github.com/drwpow/openapi-typescript/issues/1368#issuecomment-1762667672)). Basically this was missing from some places it should have been, and present in some places it shouldn’t (and TS lets you place it in invalid places)
- Tests added

Fix immutable types

---

.github/workflows/ci.yml
.github/workflows/release.yml

CI-only change; updates 2 GitHub actions runner versions.

Update GitHub Actions runners

---

.changeset/twelve-gifts-sort.md
packages/openapi-typescript-helpers/index.d.ts

Adds `SuccessResponseJSON` and `ErrorResponseJSON` helpers for easier usage. Before/after:
```diff
- type Response =
-   | SuccessResponse<FilterKeys<ResponseObjectMap<paths["/my/endpoint"]["get"]>, "application/json">>
-   | ErrorResponse<FilterKeys<ResponseObjectMap<paths["/my/endpoint"]["get"]>, "application/json">>;
+ type Response =
+   | SuccessResponseJSON<paths["/my/endpoint"]["get"]>
+   | ErrorResponseJSON<paths["/my/endpoint"]["get"]>;
```
Note this won’t be used in `openapi-fetch` for ✨ _reasons_ ✨. But is a useful utility.
_Note—will probably keep `Success*` and `Error*` separated for the forseeable future because they’re trivial to combine in a union, and you frequently will want to have these in different codepaths anyway._
N/A

Add SuccessResponseJSON, ErrorResponseJSON helpers

---

.changeset/nine-pigs-reply.md
packages/openapi-fetch/package.json
packages/openapi-typescript-helpers/CHANGELOG.md
packages/openapi-typescript-helpers/package.json
pnpm-lock.yaml

Publishes openapi-typescript-helpers@0.0.6 while 7.x is in beta
N/A
N/A

openapi-typescript-helpers@0.0.6

---

docs/cli.md
packages/openapi-typescript/bin/cli.js
packages/openapi-typescript/test/fixtures/redocly-flag/redocly.yaml
packages/openapi-typescript/test/fixtures/redocly/redocly.yaml

Fixes #1463 by changing `openapi-ts` to `x-openapi-ts`. This is a breaking change, but there’s a helpful migration error for users of the beta version.
- Tests updated; tests should pass

Fix Redoc CLI warning

---

packages/openapi-typescript/src/transform/path-item-object.ts
packages/openapi-typescript/test/fixtures/_parameters-test-partial.yaml
packages/openapi-typescript/test/fixtures/parameters-test.yaml
packages/openapi-typescript/test/index.test.ts

openapi-typescript already support parameters deduplication but it doesn't care about `$ref`.
so if schema has `$ref` parameter with same key, it will be invalid typescript types.
I used `ctx.resolve` method but I don't know it's reasonable.

support $ref on deduplication of operator-object and path-item parameters

---

docs/about.md
docs/advanced.md
docs/cli.md
packages/openapi-fetch/README.md
packages/openapi-typescript/CONTRIBUTING.md

Just some small typos I noticed while reading through the docs.

docs: fixing various typos in the docs

---

.changeset/large-ways-cheat.md
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/examples/octokit-ghes-3.6-diff-to-api.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/schema-object.test.ts

Fixes #1407
Correctly transform untyped nullable field to `unknown` instead of `Record<string, unknown> | null`
First PR, so are there any test cases I'm missing? Anything I should add? Anything I should keep in mind going forward?

fix: correctly transform untyped nullable field

---

packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/index.test.ts
packages/openapi-fetch/test/v7-beta.test.ts
packages/openapi-typescript-helpers/index.d.ts

Closes #1370
Improves typing of fetch function by introducing a fetchOptions generic which can then be used to report correct return type.

[feat]: parseAs options reports correct data type

---

docs/6.x/advanced.md
docs/advanced.md
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/node-api.test.ts

The most popular (and de-facto standard) .NET Core OpenAPI [NSwag package](https://github.com/RicoSuter/NSwag) uses the following:
* `x-enumNames` for `x-enum-varnames`
* `x-enumDescriptions` for ` x-enum-descriptions`
1. Take any existing file with `x-enum-varnames` and/or ` x-enum-descriptions`.  
2. Replace `x-enum-varnames` with `x-enumNames` and ` x-enum-descriptions` with `x-enumDescriptions`.
3. Generate schema with `--enum ` flag to verify results
- [x ] `docs/` updated (if necessary)

Add support for x-enumNames and x-enumDescriptions enum names

---

.changeset/blue-owls-add.md
docs/package.json
package.json
packages/openapi-fetch/examples/nextjs/package.json
packages/openapi-fetch/examples/react-query/package.json
packages/openapi-fetch/examples/sveltekit/package.json
packages/openapi-fetch/package.json
packages/openapi-typescript-helpers/package.json
packages/openapi-typescript/package.json
packages/openapi-typescript/src/utils.ts
pnpm-lock.yaml

Remove `prepare` npm-scripts and updates patch deps

Remove prepare scripts, update deps

---

docs/cli.md

Docs-only change; adds the `--enum` flag
N/A
N/A

[Docs] Add enum flag to 7.x docs

---

packages/openapi-typescript/package.json
packages/openapi-typescript/test/cjs.test.js

fix: #1482 
```
const openapiTS = require('openapi-typescript').default;
const { astToString } = require('openapi-typescript');
// output: [Function: astToString] [AsyncFunction: openapiTS]
console.log('output:',astToString, openapiTS);
```

fix(openapi-typescript): build cjs support astToString export

---

.changeset/fluffy-hounds-occur.md
packages/openapi-typescript/CHANGELOG.md
packages/openapi-typescript/package.json
packages/openapi-typescript/src/transform/parameter-object-array.ts
packages/openapi-typescript/src/transform/path-item-object.ts
packages/openapi-typescript/test/path-item-object.test.ts

Fixes #1498, where sometimes parameters would be dropped if they had the same name, different locations.
- Tests should pass

Fix missing parameters

---

packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/test/transform/schema-object/string.test.ts

Fixes #1436. This is a known issue with the TypeScript compiler (https://github.com/microsoft/TypeScript/issues/36174). This hacks it by running it through JSON.stringify and basically telling TS “this is a reference don’t touch it.” Should probably be removed eventually, but for the short-term I can’t imagine there are any practical exploits.
- Tests should pass

Fix UTF-8 chars

---

.changeset/loud-items-hope.md
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/schema-object.test.ts

The PR https://github.com/drwpow/openapi-typescript/pull/1468 was too aggressive in its use of `unknown` for nullable fields. It makes sense to use `unknown` when there is no `type` defined in the schema. But in cases where there is type information available, we should not discard it. 
The changes in the snapshots show that richer types are preserved when possible. I wrote a [comment](https://github.com/drwpow/openapi-typescript/pull/1468#issuecomment-1838526799) on the original PR relating to this, but it's possible it got missed. 
Essentially, we use the "old" behavior where we have some type info available in the schema, and the "new" behavior otherwise. The original bug report https://github.com/drwpow/openapi-typescript/issues/1407 says (emphasis mine):
> I found that when a field …

Fix: keep type information for nullable fields when possible

---

.changeset/sixty-oranges-arrive.md
packages/openapi-fetch/src/index.d.ts

Adds a ClientMethod utility type to simplify the object definition of the return type of createClient.
This is a refactor adding a utility type and cleaning up some code. All tests should pass and no dependencies should be affected. Have a look at it and see if it seems more readable.
None of these apply to this change. It should not affect tests, not affect docs, and not touch the examples.

refactor(openapi-fetch): simplify createClient types

---

docs/openapi-fetch/api.md
docs/openapi-fetch/middleware-auth.md
package.json
packages/openapi-fetch/examples/nextjs/package.json
packages/openapi-typescript/package.json
pnpm-lock.yaml

Updates internal deps, and some minor docs cleanup
N/A
N/A

[chore] Update deps

---

docs/openapi-fetch/about.md

Fixes typos, shortening language
N/A
N/A

Docs fixes

---

.changeset/breezy-trees-brake.md
packages/openapi-typescript/src/transform/operation-object.ts
packages/openapi-typescript/src/transform/path-item-object.ts
packages/openapi-typescript/src/transform/paths-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/src/utils.ts
packages/openapi-typescript/test/operation-object.test.ts
packages/openapi-typescript/test/utils.test.ts

First, thanks for `openapi-typescript`!
I came across a generation failure when compiling the spec below (Azure OpenAI inference).
It appears some operations are defined with one single parameter object, not as array - see an example [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-12-01-preview/examples/audio_transcription_object.json).
I am not 100% sure this is valid OpenAPI, but since `openapi-typescript@7` compiles it successfully, I thought it would be good to fix the problem in `6.x`.
```
openapi-typescript https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-12-01-preview/inference.json …
```

Support single operation parameter

---

.changeset/quiet-seals-speak.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/index.test.ts
packages/openapi-fetch/test/v7-beta.test.ts

Fixes #1544 
Tests should pass

Fix error fallback for invalid JSON

---

.changeset/nasty-squids-collect.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/index.test.ts
packages/openapi-fetch/test/v7-beta.test.ts

`Content-Type` header with multipart boundary set by `Request()` is currently stripped after being set since `v0.8.2`.
#1548 Requests with FormData bodies are currently failing since `v0.8.2`
Had to alter test case for `Content-Type` check in case of FormData body.
Additional test cases covering `FormData` with a file Blob would help match `'content-type' => 'multipart/form-data; boundary=----formdata-undici-0.6976734701101202'`

Unset Content-Type for FormData as request body before Request() constructor call

---

.changeset/olive-dots-sing.md
packages/openapi-typescript/src/transform/path-item-object.ts
packages/openapi-typescript/test/index.test.ts

Fixes #1542
A [recent change](https://github.com/Redocly/redocly-cli/pull/1408) to redocly affected the way JSON pointers are parsed, causing operation IDs with the "#" character to generate the incorrect type mapping to operations referenced in the path item object. This works around the issue by replacing "#" characters in operation IDs with a "/" character.

fix: replace # characters in operation IDs with a slash

---

packages/openapi-fetch/test/index.bench.js

Update bench to use openapi-typescript correctly. 
Create and reuse the fetch method instead of instantiating it on every invocation.
This should speed up the benchmark slightly.
This change moves the method creation outside of the bench

update openapi-typescript-fetch bench

---

packages/openapi-typescript/src/transform/parameters-array.ts
packages/openapi-typescript/test/transform/operation-object.test.ts

fixes #1532 
added test demonstrating the fix

fix: --exclude-deprecated flag is not applied to query and path

---

pnpm-lock.yaml
test/bin/cli.test.js
test/opts/expected/remote-schema.ts
test/opts/fixtures/remote-schema/spec.yml
test/v2/index.test.js
test/v3/index.test.js

The pnpm lockfile version is bumped to 6.0. I ran `pnpm install` and it automatically did this, so I figure probably a good idea to commit upstream...
I'm doing this because I want to make other changes (which will be in a subsequent PR)
Edit: Also had to fix the remote reference to test files since they no longer exist on main.
Dunno, tests pass?
Unit tests updated, rest were n/a!

[version 5.x] chore: Bump the pnpm lockfile version to 6.0 and fix tests

---

packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/lib/utils.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/discriminators.test.ts
packages/openapi-typescript/test/test-helpers.ts
packages/openapi-typescript/test/transform/schema-object/composition.test.ts

This PR tries to solve the ignored discriminator mappings for oneOf compositions. More details here: https://github.com/drwpow/openapi-typescript/issues/1572
I am unsure if changing the schemaObject is something we really want to do. But this is very fast and even solves the allOf compositions for discriminated objects with inheritance.
Added 2 tests as well for the new cases.
All other discriminator tests are now failing. I checked a few cases and saw actual improvements to the generated types for example in the DigitalOcean types. This needs to be discussed of course.

Discriminator Mapping Support for oneOf composition

---

.changeset/unlucky-pumpkins-march.md
packages/openapi-fetch/examples/nextjs/package.json
packages/openapi-fetch/package.json
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/test/index.test.ts
packages/openapi-fetch/test/v7-beta.test.ts
packages/openapi-fetch/tsconfig.json
packages/openapi-typescript-helpers/index.d.ts
packages/openapi-typescript/package.json
packages/openapi-typescript/test/index.test.ts
packages/openapi-typescript/test/lib/ts.test.ts
packages/openapi-typescript/test/transform/operation-object.test.ts
packages/openapi-typescript/test/yaml.test.ts
packages/openapi-typescript/tsconfig.json
pnpm-lock.yaml
tsconfig.json

Fixes #1549 by re-enabling `skipLibCheck: true`. Also updates some insignificant deps to make the fix easier.
The only significant changes are in `openapi-fetch`; all the other noise is from a type error from Vite/Vitest 🙃. There are probably other ways to have dealt with it, but this was the simplest. It seems to be [an upstream in issue in Rollup (maybe; who knows)](https://github.com/vitest-dev/vitest/issues/4567)
- The existing TS checks will fail now

Fix TS errors

---

docs/openapi-fetch/index.md
packages/openapi-fetch/README.md

Benchmarks are hard. I find _showing something rather than nothing_ is useful, but it needs so many caveats and asterisks. I also rounded the numbers (fairly) to reflect a lot of fluctuation they’ve had over time.
I feel like saying “openapi-fetch is faster” is an empty statement; benchmarks are important. However getting accurate benchmarks on _how much_ faster is so tricky to get right. But I will always accept PRs [like this](https://github.com/drwpow/openapi-typescript/pull/1566) that improve the accuracy and fairness of these benchmarks.
N/A
N/A

[chore] Update benchmarks (again)

---

.github/FUNDING.yml

This will add a **COMPLETELY OPTIONAL** sponsorship button to this GitHub Repo. For now, this only adds GitHub Sponsors and nothing else. But long-term, I’m interested in whatever fits this project best.
- **Why?**
I maintain openapi-typescript in my free time and don’t receive any financial support. Receiving funding allows me to carve out additional time to support this library.
- **What will sponsors get?**
<abbr title="to be determined">TBD</abbr>! This is my first time accepting any funding, really. Probably logo placement. Probably a mention somewhere in the docs and/or README. Probably other things. I am learning about how this works.
- **Where will the money go?**
Also <abbr title="to be determined">TBD</abbr>. It depends on the level of sponsorship. I plan on using the money to …

Add GitHub Sponsorship

---

.changeset/few-tomatoes-try.md
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/test/fixtures/api.d.ts
packages/openapi-fetch/test/index.test.ts

This is a simple change that for now only allow to select the content type of the response. Inspired by the @NikolaStojicic patch. 
Fix https://github.com/drwpow/openapi-typescript/issues/1291 
This solution is not perfect but allow to fix the issue. Clearly a more robust solution could be to infer the `MediaType` by reading the `Accept` header. If multiple content and the `Accept` header not set, the lib could fallback to an `unknown` data.

Allow to select the response content type

---

.changeset/gorgeous-planes-rhyme.md
packages/openapi-fetch/src/index.d.ts

Fix the custom fetch type.
The custom fetch type does not strictly adhere to the parameter type when calling.
https://github.com/drwpow/openapi-typescript/blob/4e06f86934e11f3dbc3aabee4b4e61dd62680782/packages/openapi-fetch/src/index.js#L101
It results in the wrong type checking when using the custom fetch.

Fix custom fetch type

---

docs/openapi-fetch/testing.md
packages/openapi-fetch/package.json
packages/openapi-fetch/test/fixtures/api.d.ts
packages/openapi-fetch/test/fixtures/api.yaml
packages/openapi-fetch/test/fixtures/mock-server.ts
packages/openapi-fetch/test/fixtures/v7-beta.d.ts
packages/openapi-fetch/test/index.bench.js
packages/openapi-fetch/test/index.test.ts
packages/openapi-fetch/test/v7-beta.test.ts
pnpm-lock.yaml

- replaces vitest-fetch-mock with msw in openapi-fetch tests (including `index.bench.js`)
Fixes #1581
I've made an effort to keep the existing tests as close as possible to their original implementation, with the exception of replacing `mockFetch*` with the equivalent `msw` test handler. Due to `msw`, it's necessary to pass `baseUrl` around to ensure we're using the correct request URLs. Therefore, it has been provided for each `createClient` and equivalent test handler.
Please note, the current usage of `msw` contradicts `msw`'s best practices ([Avoid Request Assertions](https://mswjs.io/docs/best-practices/avoid-request-assertions)). However, given the nature of this library, I believe this approach is acceptable in this context. In most of these tests, we aim to validate that the …

replace vitest-fetch-mock with msw

---

packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/test/lib/ts.test.ts

- append `ValueMinus` string to enum member names starting with a `-`, if a name is not explicitly provided
- example:
```ts
enum ErrorCode {
ValueMinus1 = -1,
Value1 = 1
}
```
- create negative numeric enum member values using `ts.factory.createPrefixUnaryExpression()`
- this is forced by: https://github.com/microsoft/TypeScript/pull/56570 (present in Typescript 5.4)
When there is no name explicitly provided for them, numeric enum member names are constructed by prefixing the number with a `Value` string
The code did not take negative numbers into account, which resulted in enum members like:
```ts
enum ErrorCode {
_1 = -1,
Value1 = 1
}
```
Negative numeric enum members are not unusual in C# projects, and when combined with tools autogenerating OpenAPI schemas (i.e. Swashbuckle, NSwag), …

Handle negative numeric enum values

---

.changeset/tender-ducks-own.md
.gitignore
packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/lib/ts.test.ts

Readonly modifier is not applicable to Typescript enum.
This PR makes sure the readonly modifiers is not applied on enum when the --immutable option is used.
Related discussion
https://github.com/drwpow/openapi-typescript/issues/1368#issuecomment-2025501642
A question would be how to test this ? As I did not found a way to test with the global --immutable option.
Alternatively I added a test for the 'export' modifier that is used in the code.

Do not add readonly on enum with the immutable option,

---

packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/scripts/update-examples.ts
packages/openapi-typescript/src/lib/utils.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/discriminators.test.ts
packages/openapi-typescript/test/transform/schema-object/composition.test.ts

I noticed that the current implementation for discriminators inherited from a base class is not working when the final objects are used in anyOf or oneOf. These combinations will omit the discriminator property from the final object and result in an invalid type:
```json
{
"oneOf": [
{ "$ref": "#/components/schemas/Cat" },
{ "$ref": "#/components/schemas/Dog" },
]
}
```
```typescript
type AnimalSighting = Omit<components["schemas"]["Cat"], "petType"> | Omit<components["schemas"]["Dog"], "petType">;
const sighting: AnimalSighting = {
petType: 'Cat'; // <= without petType we can't use the discriminator in Typescript
}
```
The [OpenAPI specification on discriminators](https://spec.openapis.org/oas/v3.1.0#discriminator-object) states the following:
> In both the oneOf and anyOf use cases, all …

Bugfix for discriminators using allOf

---

.changeset/gold-worms-wave.md
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/test/fixtures/api.d.ts
packages/openapi-fetch/test/fixtures/api.yaml
packages/openapi-fetch/test/index.test-d.ts
packages/openapi-typescript-helpers/index.d.ts

Fixes #1609 
I've added a new kind of test — Vitest type test, to verify the correctness of this solution.

Fix type discrimination for non-overlapping content types

---

package.json
packages/openapi-fetch/examples/nextjs/package.json
packages/openapi-fetch/examples/react-query/package.json
packages/openapi-fetch/examples/sveltekit/package.json
packages/openapi-fetch/package.json
packages/openapi-fetch/test/fixtures/v7-beta.d.ts
packages/openapi-fetch/test/index.test.ts
packages/openapi-fetch/test/v7-beta.test.ts
packages/openapi-typescript-helpers/package.json
packages/openapi-typescript/package.json
pnpm-lock.yaml

This won’t fix CI on merge, but it fixes a test error that will make the fix easier. The root cause is `openapi-typescript-helpers` needs a version bump (and `openapi-fetch` needs a patch release from that bumped version), and just for testing I’ll release that new version first and test it works locally before releasing `openapi-fetch`. So this is just a chore PR that tees that up.
N/A
N/A

Fix Test error

---

docs/cli.md
packages/openapi-typescript/bin/cli.js
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/test-helpers.ts
packages/openapi-typescript/test/transform/schema-object/object.test.ts

Closes #1570.
Adds a `propertiesRequired` option to the Node.js API and global context and exposes this as `--properties-required` in the CLI.
Schema objects are allowed to have a `required` property that is set to an array of keys in `properties` that are considered required. The default for `required` is `[]` as specified by https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.5.3 and adopted by openapi via https://swagger.io/specification/#data-types. This may not be the intent of many API designers, so the `propertiesRequired` option changes the interpretation of section 6.5.3 from
> Omitting this keyword has the same behavior as an empty array.
to the following:
> Omitting this keyword has the same behavior as specifying an array containing the …

Add propertiesRequired option to Node.js API and CLI #1570

---

.changeset/smooth-cameras-fail.md
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/transform/request-body-object.test.ts

Closes #1619
I'm not sure if this is the right place to call the transform yet. So please give me some feedback on wether it is ok there or if it should go somewhere else. I've

fix(schema-object): transform toplevel schema object

---

packages/openapi-fetch/package.json
packages/openapi-typescript/scripts/update-examples.ts
pnpm-lock.yaml

pnpm v9 changed local workspace resolution—intentionally or not (but I’ll assume intentionally). I also think _most_ publish scripts handle `workspace`s now. At any rate, fix local dev first, then worry about publishing later.

Fix pnpm 9.x package resolution

---

.changeset/orange-coins-pull.md
packages/openapi-fetch/src/index.d.ts

This pull request fixs request options type when there is required keys and when set them the type the typing for the other optional properties dissapear, below is a example the current behavior vs the new behavior with this pull request
[current implementation](https://streamable.com/7a5b00)
[new implementation](https://streamable.com/c8l6bx)

fix types on passing request options

---

packages/openapi-fetch/package.json
packages/openapi-typescript/package.json
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/transform/schema-object/array.test.ts
packages/openapi-typescript/test/transform/schema-object/object.test.ts
pnpm-lock.yaml

Fixes immutable arrays ([comment](https://github.com/drwpow/openapi-typescript/issues/1368#issuecomment-2031466328))

Fix immutable arrays

---

.changeset/gorgeous-people-smile.md
packages/openapi-typescript/src/types.ts

Fix SecurityRequirementsObject to allow partial security schemes

---

.changeset/red-pants-cover.md
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/index.test.ts

This pull request lets request object attach custom properties like `next` prop on nextjs environment.
It should works

add custom properties to request object

---

packages/openapi-fetch/package.json
pnpm-lock.yaml

Bumps the version of openapi-typescript-fetch for benchmark
No code changes, all tests should pass

bump openapi-typescript-fetch version

---

packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/test/transform/schema-object/number.test.ts

This change fixes an error when a negative number appeared in an enum.
Run the unit tests with and without the change. The `src` change was basically copied from the `tsEnumMember` function.

fix: enums containing negative numbers

---

docs/cli.md
docs/zh/cli.md
packages/openapi-typescript/bin/cli.js
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/lib/ts.test.ts
packages/openapi-typescript/test/node-api.test.ts
packages/openapi-typescript/test/test-helpers.ts

This adds a `--enum-values` flag to the CLI.
If `true`, for each enum an array of valid values is exported. The default is `false`.
See #1616 for details and motivation.

add flag for exporting enum value arrays #1616

---

package.json
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/transform/schema-object/string.test.ts
pnpm-lock.yaml

Fixes [an issue called out in the v7 Preview thread](https://github.com/drwpow/openapi-typescript/issues/1368#issuecomment-1794837901) where a schema object with `default` + nullable wouldn’t generate as-expected.
- Tests added; tests should pass

Fix schema objects with default + nullable

---

.changeset/wet-apples-hide.md
packages/openapi-fetch/src/index.js

fix: only add custom properties that aren't in the request object

---

docs/openapi-fetch/api.md
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/index.test.ts

Add the `req` as thrid params of the onResponse middleware. Its useful to create log on the on response (the `Response` did not contains some information of the original request)

Expose original request on Middleware.onResponse

---

packages/openapi-typescript/examples/octokit-ghes-3.6-diff-to-api.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/transform/request-body-object.test.ts

Noticed that when a request body field had a `default` value, that it was being specified as required. This would change it to be treated like a parameter with a default value.
Let me know if the premise correct and then I could look into updating the tests.

requestBody fields optional even with defaults

---

.github/CODEOWNERS
.github/FUNDING.yml
CODE_OF_CONDUCT.md
GOVERNANCE.md
README.md
docs/.vitepress/shared.ts

[See the Discussion announcement](https://github.com/openapi-ts/openapi-typescript/discussions/1693) for more context. This adds Governance, and replaces GitHub Sponsors with Open Collective as the official sponsorship method.
N/A
N/A

Add governance, update funding

---

.changeset/config.json
.github/ISSUE_TEMPLATE/bug-report-fetch.md
.github/ISSUE_TEMPLATE/bug-report-ts.md
.github/ISSUE_TEMPLATE/feature-request-fetch.md
.github/ISSUE_TEMPLATE/feature-request-ts.md
README.md
docs/.vitepress/en.ts
docs/.vitepress/shared.ts
docs/.vitepress/zh.ts
docs/6.x/introduction.md
docs/CONTRIBUTING.md
docs/index.md
docs/introduction.md
docs/migration-guide.md
docs/openapi-fetch/examples.md
docs/openapi-fetch/index.md
docs/zh/index.md
docs/zh/introduction.md
docs/zh/openapi-fetch/examples.md
packages/openapi-fetch/CHANGELOG.md
packages/openapi-fetch/CONTRIBUTING.md
packages/openapi-fetch/README.md
packages/openapi-fetch/package.json
packages/openapi-typescript-helpers/CHANGELOG.md
packages/openapi-typescript-helpers/package.json
packages/openapi-typescript/CHANGELOG.md
packages/openapi-typescript/CONTRIBUTING.md
packages/openapi-typescript/package.json
packages/openapi-typescript/src/transform/path-item-object.ts
pnpm-lock.yaml

Chore: Replaces `drwpow/openapi-typescript` → `openapi-ts/openapi-typescript`. GitHub is currently redirecting, but no guarantee how long. And a redirect isn’t great to rely on.
N/A; internal change.
N/A

Update GitHub org

---

packages/openapi-fetch/CHANGELOG.md
packages/openapi-fetch/package.json

Release `openapi-fetch@0.9.8`. Hopefully the last manual release 🤞
- Only releasing already-merged & tested changes; no additional changes.
N/A

openapi-fetch@0.9.8

---

docs/src/content/docs/cli.md
packages/openapi-typescript/bin/cli.js

This change will make the CLI command support an environment variable called http_proxy. This is a standard environment variable in environments where a http proxy is required to access the internet.
Setup a http proxy server. Then start the openapi-typescript CLI command with an environment variable http_proxy. E.g.:
```
HTTP_PROXY=http://myproxy.company.lan:1234 ./node_modules/.bin/openapi-typescript 
```

Setup proxy support using environment variable HTTP_PROXY

---

packages/openapi-fetch/examples/react-query/package.json
packages/openapi-fetch/examples/react-query/src/hooks/queries.ts
packages/openapi-fetch/examples/sveltekit/package.json
packages/openapi-fetch/examples/vue-3/package.json
packages/openapi-fetch/test/index.test.ts
pnpm-lock.yaml

No code changes. Expands header test suite to make more granular assertions over headers passed through middleware, all the way to the final request.
- Tests updated; tests should pass.

Add additional headers tests

---

.changeset/wet-days-crash.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/index.test.ts

Fixes https://github.com/drwpow/openapi-typescript/issues/1596

Apply encodeURIComponent on path parameter value

---

packages/openapi-typescript/tsconfig.json

Hi, @drwpow! I've encountered an issue where VSCode's debugger cannot correctly navigate to the source files.
- Removed `sourceRoot` configuration from `tsconfig.json` .
- This fix resolves the issue where source maps were not correctly mapping to the original TypeScript files.

Remove sourceRoot configuration to enable proper source file mapping

---

docs/cli.md
docs/zh/cli.md

docs: update

---

.changeset/serious-days-live.md
packages/openapi-typescript/src/transform/schema-object.ts

Make sure `result` is an object before using the `in` operator. Fixes the following errors when generating a schema:
```bash
node_modules/openapi-typescript/dist/transform/schema-object.js:149
if ("schema" in result) {
^
TypeError: Cannot use 'in' operator to search for 'schema' in UUID
at transformSchemaObjectCore (node_modules/openapi-typescript/dist/transform/schema-object.js:149:30)
at transformSchemaObjectWithComposition (node_modules/openapi-typescript/dist/transform/schema-object.js:108:28)
at transformSchemaObject (node_modules/openapi-typescript/dist/transform/schema-object.js:6:18)
at transformParameterObject (node_modules/openapi-typescript/dist/transform/parameter-object.js:4:37)
at transformParametersArray (node_modules/openapi-typescript/dist/transform/parameters-array.js:30: …
```

Check `result` type before using `in` operator

---

packages/openapi-fetch/src/index.js

https://github.com/openapi-ts/openapi-typescript/issues/1695
#1694
The `instanceof` was throwing an error when the body was falsy.

fix: add verification when request body is falsy

---

.changeset/plenty-islands-tie.md
packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/test/lib/ts.test.ts
packages/openapi-typescript/test/transform/components-object.test.ts

fix: Generate valid types for referenced nested properties

---

docs/zh/openapi-fetch/middleware-auth.md

Fix misquote request in middleware-auth.md

---

docs/node.md

Fixes #1688
Verify example from docs:
```ts
import path from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";
const BLOB = ts.factory.createTypeReferenceNode(ts.factory.createIdentifier("Blob")); // `Blob`
const NULL = ts.factory.createLiteralTypeNode(ts.factory.createNull()); // `null`
const baseDir = path.dirname(fileURLToPath(import.meta.url));
const mySchema = new URL(path.resolve(baseDir, "../test1.yaml"), import.meta.url);
const ast = await openapiTS(mySchema, {
transform(schemaObject, metadata) {
if (schemaObject.format === "binary") {
return {
schema: schemaObject.nullable ? ts.factory.createUnionTypeNode([BLOB, NULL]) : BLOB,
questionToken: true,
};
}
},
}); …
```

fix(docs): createTypeReferenceNode in transform examples

---

docs/advanced.md

The example in the enum extensions sections of the docs needs to have `--enum` specified on the command line to generate as expected, so I added a note for that so future developers aren't as confused as I was.
This is a docs-only change, not much to review.

Add enum notes

---

packages/openapi-typescript/bin/cli.js

Fix #1745 
Tests added; tests should pass

fix: resolve issue with saving output using full file paths

---

docs/node.md

The Redocly config field on OpenAPITSOptions is named `redocly`, not `redoc`. This corrects the code example.

docs: correct redocly config example

---

packages/openapi-typescript/src/index.ts

When I was using the api, I found that some of the default exports inside were unusable
The default export method can be used correctly

fix: export default exports correctly

---

.changeset/brave-lizards-juggle.md
packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/test/node-api.test.ts

#1722
Made the following changes:
- Quote the name if it consists entirely of invalid characters.
- Replace only the invalid characters with "_" if they are part of the name.
The existing logic that replaces invalid characters within a key name with "_" has been kept. Additionally, by quoting the name when it consists entirely of invalid characters, it helps prevent errors.
Ensure that the test passes.

fix: Enum option cannot generate enums if values are not valid property names

---

.changeset/little-pets-perform.md
docs/node.md
docs/zh/node.md
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/transform/index.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/index.test.ts

#1754 - Add the inject option
All the tests should pass

feat: Add the inject option

---

.changeset/stupid-pans-hug.md
docs/cli.md
docs/zh/cli.md
packages/openapi-typescript/bin/cli.js

#1615, #1738- Add check option

feat: Add check option

---

.changeset/eight-pants-attack.md
packages/openapi-typescript/bin/cli.js
packages/openapi-typescript/test/cli.test.ts

Fix --properties-required-by-default flag not working. #1651 
It was just simple typo.

fix: --properties-required-by-default flag

---

.changeset/chilled-radios-remain.md
packages/openapi-typescript/bin/cli.js
packages/openapi-typescript/scripts/download-schemas.ts
packages/openapi-typescript/scripts/update-examples.ts
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/lib/redoc.ts
packages/openapi-typescript/src/transform/components-object.ts
packages/openapi-typescript/src/transform/index.ts
packages/openapi-typescript/src/transform/paths-object.ts

- Running openapi-typescript through Bazel results in a `ReferenceError: performance is not defined` error
- This PR adds an explicit `import { performance } from "node:perf_hooks"` whenever `performance` is used in the code.
- I've tested that this fixes my Bazel compability issues.
- Make sure I didn't miss any usages of `performance`.
- Let me know if there's a reason why the import was omitted.

fix: add explicit import of performance to fix bazel compatibility issues

---

.changeset/rich-olives-scream.md
packages/openapi-typescript/src/transform/header-object.ts
packages/openapi-typescript/src/transform/request-body-object.ts
packages/openapi-typescript/src/transform/response-object.ts
packages/openapi-typescript/test/transform/request-body-object.test.ts
packages/openapi-typescript/test/transform/response-object.test.ts

references #369
There is a case when there is no content in request or response, at the moment openapi-typescript panic in such cases

fix: schema.content might be omitted

---

.changeset/little-pets-perform.md
.changeset/stupid-pans-hug.md

`openapi-typescript-docs` isn’t an actual package, so it’s blocking releases until it’s removed 
N/A

Unblock changesets release

---

.changeset/soft-roses-teach.md
packages/openapi-typescript-helpers/package.json

Fix https://github.com/openapi-ts/openapi-typescript/issues/1749
By default, `npm publish` respects `.gitignore` so that [the npm distribution](https://www.npmjs.com/package/openapi-typescript-helpers/v/0.0.9?activeTab=code) doesn't include `index.d.cts`.
[`package.ison` points to it](https://github.com/yukukotani/openapi-typescript/blob/510cff34ce11a007365463bb3fa498cabc5eb57c/packages/openapi-typescript-helpers/package.json#L20) even though it's missing, and this results in fallback to `index.cjs`.  This causes that types from `openapi-typescript-helpers` to be treated as `any`.
This PR adds `files` field in `package.json` to explicitly declare `index.d.cts` to be included in the distribution.
The output of `npm pack` includes `package.d.cts`.

fix(openapi-typescript-helpers): keep index.d.cts in npm distribution

---

.changeset/warm-plums-wait.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/fixtures/api.d.ts
packages/openapi-fetch/test/fixtures/api.yaml
packages/openapi-fetch/test/index.test.ts

I was trying to use openapi-fetch for file uploading, but by default that wasn't possible (using `multipart/form-data`). Looking at the source code I noticed that part of the solution for fixing it seemed to be missing as `defaultBodySerializer` never allows `FormData` to be passed through it:
```js
if (requestInit.body) {
// Here, bodySerializer always returns a JSON string by default
requestInit.body = bodySerializer(requestInit.body);
// remove `Content-Type` if serialized body is FormData; browser will correctly set Content-Type & boundary expression
if (requestInit.body instanceof FormData) {
requestInit.headers.delete("Content-Type");
}
}
```
I'm trying to fix that in this PR by allowing `FormData` to be passed through the `defaultBodySerializer` enabling file uploads with …

feat: allow form data through default body serializer

---

LICENSE
biome.json
packages/openapi-typescript-helpers/package.json

Adds MIT License in root. Doesn’t change licensing of anything; just flags to GitHub the whole thing is MIT-licensed.
N/A
N/A

chore: Add LICENSE in root

---

packages/openapi-fetch/test/index.bench.js

It is not declared in package.json, so running `npx vite bench` fails.

test: remove unused nanoid import in index.bench.js

---

.changeset/chilled-rules-judge.md
packages/openapi-fetch/src/index.js

Remove unnecessary `async` keywords in object returned from `createClient`.
They simply increase code size (perf in this sense).
I stumbled upon this when working on #1791 / #1526.
I have checked that `dist/index.min.js` still contains the `async` keyword, so at least when minified with esbuild, this really contributes to bundle size.
- Check that `async` does not hint to the JIT.
All points N/A.

perf: remove unnecessary `async` keywords

---

.changeset/smooth-actors-tickle.md
packages/openapi-fetch/src/index.d.ts

This PR changes typing to avoid the global `HeadersInit`, which is declared in the DOM lib and therefore typically not included in Node projects.
Resolves #1823 
Resolves #1824

fix(openapi-fetch): don't rely on DOM types

---

.github/workflows/issue-stale.yml

Follow-up to #1795
In the GitHub stale issue workflow, change the stale issue close time to 7 days to match the comments added to the issue by the automation:
> If there is no activity in the next 7 days, the issue will be closed.
> This issue was closed because it has been inactive for 7 days since being marked as stale.
[Relevant docs](https://github.com/actions/stale?tab=readme-ov-file#all-options) for `actions/stale`.

set stale issue close time to 7 days

---

.changeset/hip-years-invite.md
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/test/index.test.ts

Adds a new `MethodResponse` utility type to `openapi-fetch` to easily reference the return type of a fetch call in your code
There are many times in a codebase where you do something like this:
```ts
async function getData(...data): Promise<Data> {
// 1) Process the data in some way
// 2) Do some other async calls like DB queries or querying other services
const { data, error } = await client.GET('/data', {});
if (error != null) { /* handle case */ }
return data;
}
```
The return type of this function is based solely on the `data` endpoint result, so it would be nice to make this relation explicitly clear
The easiest way to do this is the following code, is the following code
```ts
async function getData(): Promise<Awaited<ReturnType<typeof client.GET<'/data', {}>>>>
```
This has a …

Add MethodResponse utility type

---

.changeset/lazy-dancers-push.md
packages/openapi-fetch/package.json
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/test/no-strict-null-checks/noStrictNullChecks.test.ts
packages/openapi-fetch/test/no-strict-null-checks/tsconfig.json
packages/openapi-fetch/tsconfig.json
packages/openapi-react-query/src/index.ts
packages/openapi-typescript-helpers/index.d.ts

This PR refactors some types to remove usage of `undefined extends T` conditional types. It also adds a new test suite that is type checked with `strictNullChecks` disabled to allow for increased support of that configuration.
Resolves #1778 
See context in [this comment on the issue](https://github.com/openapi-ts/openapi-typescript/issues/1778#issuecomment-2276217668). Using `undefined extends T` only behaves as expected when `strictNullChecks` is enabled. While this configuration is highly recommended for consuming projects, it is not the default, and we should design types that also work without it when possible.
#1778 describes a case where `params` is required on calls to routes with no parameters defined or no required parameters in the spec. At least two other cases are caused by …

fix type checking when `strictNullChecks` is disabled

---

.github/workflows/size-limit.yml
package.json
pnpm-lock.yaml

ref: #1853
- added a workflow named "Size Limit" using [size-limit-action](https://github.com/andresz1/size-limit-action) to check the size of `openapi-fetch` on the main branch.
- added a size-limit section to the root package.json and defined the limit.
-  set `brotli` to false because I believe it’s better to define the limit based on simply minified values.
-  I’ve set the limit to `6.5 kB` for now, but I would appreciate your input on what the ideal size should be.
- (optional) added an npm script called `size` to allow checking the size locally. This is optional, so feel free to remove it if it’s not needed.
```
Size limit: 6.5 kB
Size:       5.96 kB with all dependencies and minified
```
- Ensure that the GitHub Actions bot comments on the PR with the results of size-limit.
N/A

feat(ci): add size-limit and apply it to openapi-fetch

---

.changeset/little-knives-design.md
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/test/index.test.ts

To achieve this, we remove unnecessary type bounds.
This fixes #1840.
- Remove unnecessary type bounds.
- Add tests for client types.
- Double check the removal of type bounds does not break anything.

fix: allow use of `PathBasedClient` with generated `paths`

---

.changeset/proud-pugs-clean.md
packages/openapi-typescript/src/transform/path-item-object.ts
packages/openapi-typescript/test/transform/path-item-object.test.ts

fix: keyedParameters use unique key

---

.changeset/silly-apes-know.md
packages/openapi-typescript-helpers/index.d.ts

fix SuccessResponseJSON and ErrorResponseJSON helpers
Should fix issue  #1785 
I tested it with the following code:
```typescript
import type { ErrorResponseJSON, SuccessResponseJSON } from "./index.d.ts";
import type { components, paths } from "./v1.d.ts";
type Expect<T extends true> = T;
type Equal<X, Y> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? true : false;
type A = ErrorResponseJSON<paths["/fact"]["get"]>;
type B = number;
type Tests = [
Expect<Equal<ErrorResponseJSON<paths["/fact"]["get"]>, components["schemas"]["Error"]>>,
Expect<Equal<SuccessResponseJSON<paths["/breeds"]["get"]>, components["schemas"]["Breed"][]>>,
];
```
I could add a test.d.ts to test the types but i thought it could (on breaking changes) break the global test script (used in ci...)

fix(openapi-typescript-helpers): fix SuccessResponseJSON and ErrorResponseJSON helpers

---

.changeset/proud-students-repeat.md
packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/node-api.test.ts

reference: #1856 
In injectFooter, by redefining ReadonlyArray, type inference for ReadonlyArray is correctly applied to the array type.
All test cases should pass

fix(openapi-typescript): type errors generated under `enumValues`

---

.changeset/rich-crews-repeat.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/index.test.ts

Resolves https://github.com/openapi-ts/openapi-typescript/issues/1695
This PR ensures that all falsy values except `undefined` i.e. `null`, `false`, `0` and `""` are treated as a valid body. This means:
- going through `bodySerializer`, when specified
- sending the body to the server
- Check the added unit tests which describe the desired behavior.
- The change in implementation itself is ridiculously simple.
- I didn't find any section describing the behavior.

Allow falsy values (except undefined) as a valid body

---

.changeset/chilled-forks-rush.md
docs/openapi-fetch/api.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/index.test.ts

Resolves #1694
**Important:** This PR touches the same code as #1825 and in-fact includes the same fix by itself. I recommend merging #1825 first.
This PR prevents Content-Type header from being set on requests with no body. This is required to ensure compatibility with strict server impls. such as [fastify](https://fastify.dev/).
- Consider checking the included tests and docs to understand the desired behavior.
- The change in the implementation is rather simple.

Do not set content-type on body-less requests

---

packages/openapi-fetch/biome.json
packages/openapi-fetch/package.json
packages/openapi-fetch/test/bench/index.bench.js
packages/openapi-fetch/test/bench/openapi-typescript-codegen.min.js
packages/openapi-fetch/vitest.config.ts
pnpm-lock.yaml

Part of #1365. #1895 removed MSW from benchmarks, but didn’t get the benchmarks working.
But it seems **removing MSW has greatly improved consistency**. I’m seeing really consistent runs for openapi-fetch, openapi-fetch (path-based), and openapi-typescript-fetch.
There’s still a missing mock needed for libraries that don’t use `globalThis.fetch` directly (axios, superagent, openapi-typescript-codegen), but that can be handled in a followup.
- `pnpm run bench:js` works in openapi-fetch
N/A

chore(openapi-fetch): Improve benchmarks

---

.changeset/signal.md
packages/openapi-react-query/src/index.ts
packages/openapi-react-query/test/index.test.tsx

feat(openapi-react-query): Pass abort signal to fetch

---

.changeset/brave-days-invent.md
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/common/request.test.ts

- allows to specify a custom `Request` class
- for more information around the motivation see #1563 
- build on the foundation of #1593 
- I removed the pre-existing `CustomRequest` class and inlined the business logic from the constructor
- added a unit test

feat(openapi-fetch): allow usage of custom Request class

---

.changeset/short-lizards-rescue.md
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/test/middleware/middleware.test.ts

This PR updates the Middleware type definition to ensure that either `onRequest` or `onResponse` must be provided, as reflected in the error:
> "Middleware must be an object with one of onRequest() or onResponse()"
(see https://github.com/openapi-ts/openapi-typescript/issues/1916)
The new type definition introduces a union that enforces this behavior, allowing the absence of both methods to be detected at compile time.
Please review the changes to ensure that the new type definition accurately reflects the expected behavior. The key point is that a type error should occur only if neither onRequest nor onResponse is provided. Additionally, please check that existing middleware implementations are unaffected by this change.
Closes #1916

Improve middleware type definition

---

docs/cli.md
docs/ja/cli.md
docs/zh/cli.md

Replaced `redoc` to `redocly` following to the changes of https://github.com/openapi-ts/openapi-typescript/pull/1645 .

docs: fix the name of cli argument

---

.changeset/real-penguins-fold.md
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/transform/schema-object/string.test.ts

fix: Support for generating enums when enums definition has null value

---

.changeset/strong-boats-drive.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/common/params.test.ts

Fixes a case where multiple empty arrays are passed as query params will create multiple orphaned ampersands in the resultant request URL
Closes https://github.com/openapi-ts/openapi-typescript/issues/1935
I decided to effectively ignore empty arrays in the querySerializer, the issue was they were returning `""` from `seralizeArrayParam` which was then caught up in the `.join("&")`. However, we could just as easily `.filter` out the empty strings and catch for the general case.

fix(openapi-fetch): Prevent orphan ampersands in query from empty arrays

---

.changeset/odd-seahorses-juggle.md
packages/openapi-typescript-helpers/index.d.ts

Since #1871,
1. SuccessResponseJSON and ErrorResponseJSON no longer return `never`, but may return a non-application/json response.
2. RequestBodyJSON returns `{ "application/json": T }` instead of `T`.
This fixes these issues.

fix(openapi-typescript-helpers): fix SuccessResponseJSON, ErrorResponseJSON and RequestBodyJSON

---

.github/workflows/release.yml

CI-change only. Adds @openapi-ts-bot user token to run the changesets action that prepares releases.
Currently, we are using the default GitHub Actions bot, which CAN’T run PR checks, which means a normal maintainer can’t merge release PRs without admin override permissions. This ensures not only release PRs run actions; it also lets maintainers approve package releases more-easily. This is a common workaround implemented by many open source repos; we just hadn’t taken the time to set this up before.
- There’s nothing to review; this may require some post-merge fixes
N/A

CI: Add bot token

---

biome.json
package.json
packages/openapi-fetch/biome.json
packages/openapi-fetch/examples/nextjs/package.json
packages/openapi-fetch/examples/react-query/package.json
packages/openapi-fetch/examples/sveltekit/package.json
packages/openapi-fetch/examples/vue-3/package.json
packages/openapi-fetch/package.json
packages/openapi-react-query/biome.json
packages/openapi-react-query/package.json
packages/openapi-react-query/src/index.ts
packages/openapi-typescript/biome.json
packages/openapi-typescript/package.json
packages/openapi-typescript/test/lib/ts.test.ts
pnpm-lock.yaml

Updates deps to fix artificial security issues
N/A

Chore: Update deps

---

.github/workflows/issue-stale.yml

Bumps up stale issue timeout from 90 days -> 180 days. Issues can be unaddressed for a little longer based on maintainer avail
N/A
N/A

CI: Increase stale issue timeout

---

.changeset/rude-pumas-wonder.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/http-methods/delete.test.ts
packages/openapi-fetch/test/never-response/never-response.test.ts

This PR updates the current behavior for handling `204` and empty responses.
`data`/`error` will not be set to `undefined` to match the generated type.
Follow-up from https://github.com/openapi-ts/openapi-typescript/pull/1937#discussion_r1785904312
Check updated tests. The type displayed for empty 204 responses (`content?: never`) will now match the returned data/error type.

feat: 204 to undefined

---

.changeset/query-options-infer.md
.changeset/query-options-queryfn.md
packages/openapi-react-query/package.json
packages/openapi-react-query/src/index.ts
packages/openapi-react-query/test/index.test.tsx

Fixes #1929, #1946. And also fixes an issue with `SkipToken` and `useSuspenseQuery`.
Added tests that reproduce the bug so if they are correct and green, the linked issues should be fixed.

fix(openapi-react-query): Fix typing of queryOptions

---

.changeset/.changeset/silver-wasps-relate.md
docs/openapi-fetch/middleware-auth.md

Fix throwing middleware example in docs
Fixes https://github.com/openapi-ts/openapi-typescript/issues/1954
Doc change only.

Fix middleware docs

---

docs/scripts/update-contributors.js

Fixes #1990 and unblocks docs builds.
Run the `update-contributors` script and see that user `davidleger95` is skipped due to their account not existing anymore.

Skip updating contributors with unavailable GitHub accounts

---

.changeset/thirty-queens-try.md
packages/openapi-typescript/src/transform/paths-object.ts
packages/openapi-typescript/test/transform/paths-object.test.ts

Make pathParamsAsTypes work with integer/boolean types
Fixes #1930 
~Also, corepack added a `packageManager` to `package.json` which is normally useful, but I can remove it if you want.~

Fix path params as types

---

.changeset/spotty-flies-knock.md
.vscode/settings.json
docs/scripts/update-contributors.js
packages/openapi-react-query/src/index.ts
packages/openapi-react-query/test/index.test.tsx

Fix invalid data check in query/mutation fn

---

.changeset/heavy-kangaroos-beam.md
docs/openapi-fetch/api.md
docs/openapi-fetch/middleware-auth.md
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/middleware/middleware.test.ts

This PR adds an optional `onError` handler to the middleware feature. It allows handling errors thrown by `fetch` in three ways:
- return nothing which means that the error will still be thrown, but useful for logging,
```ts
client.use({
onError({ error }) {
console.error(error);
return;
},
});
```
- return another instance of `Error` to be thrown instead,
```ts
client.use({
onError({ error }) {
return new Error("Oops", { cause: error });
},
});
```
- or return a new instance of `Response` which means that the `fetch` call will proceed as successful.
```ts
client.use({
onError({ error }) {
return Response.json({ message: 'nothing to see' });
},
});
```
See additional tests in [`packages/openapi-fetch/test/middleware/middleware.test.ts`](https://github.com/openapi-ts/openapi-typescript/pull …

feat(openapi-fetch): add onError handler to middleware

---

.changeset/three-bobcats-mate.md
packages/openapi-typescript/src/lib/redoc.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/invalid.test.ts

- improved error messages - added locations to help find the problem in schema
- do not throw error on first problem - display all the problems with the schema before throwing an error - helps to find out how many things are broken in schema
- repeated code moved to internal method, reused in both Validation and Bundling
Examples: 
- from ` ✘  Can't resolve $ref `  to ` ✘  Can't resolve $ref at #/components/schemas/Pet/properties/type`
- from `Expected SchemaObject, received Array` to `Expected SchemaObject, received Array at #/components/schemas/someSchema`
Apart of more explicit error messages the only change is in not throwing the first `problem`, but rather display all the problems to help quickly fix them before the next run. This is not affecting the application flow, as the Error …

fix(openapi-typescript): include location in error messages

---

packages/openapi-fetch/CHANGELOG.md
packages/openapi-fetch/package.json
packages/openapi-react-query/CHANGELOG.md
packages/openapi-react-query/package.json

Fixes #2032 by refreshing bad packages and forcing a manual republish. Should work because of #2036.
N/A
N/A

Manually version packages

---

packages/openapi-fetch/.npmignore
packages/openapi-metadata/.npmignore
packages/openapi-react-query/.npmignore
packages/openapi-typescript-helpers/.npmignore
packages/openapi-typescript/.npmignore

`.turbo` folders accidentally appearing in publish (despite being in `.gitignore`?). This ensures we always omit them from npm builds (it’s just harmless metadata, but it’s still package noise that shouldn’t be there).
N/A
N/A

Ignore .turbo from publishing

---

package.json

A recent PR increased the weight of openapi-fetch by ~0.2kb. This is all perfectly-safe, and normal, especially with handwritten code.
The size-limits check isn’t to try to get us to participate in [code golf](https://en.wikipedia.org/wiki/Code_golf) or enforce arbitrary limits. Especially in openapi-fetch’s case, the purpose is to:
1. Guard against sneaky package dependencies (openapi-fetch as of now should have no dependencies; just a single one could increase it by 30kb or more!)
2. Set a baseline for size. We just want to have a gauge of roughly how big this package is (also so we know when to Find + Replace all the docs that brag about its size :P)
3. Help reviewers catch unintentional increases. It is very easy to miss a one-line package import in a PR review. This should be an …

Increase size limit for openapi-fetch

---

docs/package.json
package.json
packages/openapi-fetch/examples/react-query/package.json
packages/openapi-fetch/examples/sveltekit/package.json
packages/openapi-fetch/examples/vue-3/package.json
packages/openapi-fetch/package.json
packages/openapi-react-query/package.json
packages/openapi-react-query/vitest.config.ts
packages/swr-openapi/package.json
pnpm-lock.yaml

Adds a `pnpm run -w build` to build all packages for docs.
N/A

Docs: fix build

---

docs/.vitepress/en.ts

- I fixed a problem that caused a 404 on the destination page when clicking on the About link in the openapi-react-query in the sidebar when opening the URL https://openapi-ts.dev/openapi-react-query/.
- After this fix, the about page of openapi-react-query will open correctly
- Now when you press about, it used to open https://openapi-ts.dev/openapi-react-query/openapi-react-query/about, but now it opens https://openapi-ts.dev/openapi-react-query/about has been modified to open.
- Make sure the about page of openapi-react-query opens correctly in the preview page docs.

fix 404 about page link in sidebar openapi-react-query

---

.changeset/healthy-rabbits-flow.md
docs/cli.md
packages/openapi-typescript/bin/cli.js
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/transform/index.ts
packages/openapi-typescript/src/transform/paths-enum.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/index.test.ts
packages/openapi-typescript/test/test-helpers.ts
packages/openapi-typescript/test/transform/paths-enum.test.ts

Brings back `--make-paths-enum` option to generate `ApiPaths` enum.
See: https://github.com/openapi-ts/openapi-typescript/issues/1057

feat: brings back --make-paths-enum option to generate ApiPaths enum

---

.changeset/strange-cherries-collect.md
packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/index.test.ts

Allow all types except UNKNOWN to be nullable.
Fixes https://github.com/openapi-ts/openapi-typescript/issues/1821 and https://github.com/openapi-ts/openapi-typescript/issues/1940 .
I re-applied https://github.com/openapi-ts/openapi-typescript/pull/1959 (it didn't move for a while)
I added tests for the new syntax for OAS 3.1 (not the one with `oneOf`, but with a `type` array, as [documented here](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0#:~:text=Swap%20nullable%20for%20type%20arrays)).

fix(openapi-typescript): handle nullable schemas

---

.changeset/hot-pants-sit.md
packages/openapi-fetch/src/index.d.ts
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/http-methods/request.test.ts

This Pull request closes #1808 by providing a `request` method that accept a method as its first arguments allowing to pass any `HttpMethod`. Making library authors' life easier.
This does not introduce any breaking change.
A new `request` should be available on the client that **must behave exactly** like the other `GET`, `OPTIONS`, etc methods but with the ability to pass the HttpMethod as first parameter.

feat(openapi-fetch): add support for arbitrary method

---

.github/ISSUE_TEMPLATE/01_openapi-typescript-bug.yml
.github/ISSUE_TEMPLATE/01_openapi-typescript-feat.yml
.github/ISSUE_TEMPLATE/02_openapi-fetch-bug.yml
.github/ISSUE_TEMPLATE/02_openapi-fetch-feat.yml
.github/ISSUE_TEMPLATE/03_openapi-react-query-bug.yml
.github/ISSUE_TEMPLATE/03_openapi-react-query-feat.yml
.github/ISSUE_TEMPLATE/04_swr-openapi-bug.yml
.github/ISSUE_TEMPLATE/04_swr-openapi-feat.yml
.github/ISSUE_TEMPLATE/config.yml

Tried to use the new [Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) but we have some config issues that prevent them from showing properly. This fixes that.
Also does some minor massaging for names and descriptions so they make more sense in context. Switched from grouping bugs together, and features together, to grouping by library first, then bug/feature 2nd. 
N/A
N/A

Fix issue templates

---

.github/workflows/issue.yml

GitHub, by default, doesn’t allow auto issue assignment. Try out a GitHub action to automatically round-robin select one maintainer to triage the issue, and follow up.
- Any additional settings desirable?
- Any other GitHub Actions we should evaluate (I’ll admit I just picked the first one I found)?
N/A

Auto-assign issues

---

.github/ISSUE_TEMPLATE/01_openapi-typescript-bug.yml
.github/ISSUE_TEMPLATE/01_openapi-typescript-feat.yml
.github/ISSUE_TEMPLATE/02_openapi-fetch-bug.yml
.github/ISSUE_TEMPLATE/02_openapi-fetch-feat.yml
.github/ISSUE_TEMPLATE/03_openapi-react-query-bug.yml
.github/ISSUE_TEMPLATE/03_openapi-react-query-feat.yml
.github/ISSUE_TEMPLATE/04_swr-openapi-bug.yml
.github/ISSUE_TEMPLATE/04_swr-openapi-feat.yml

Additional fixes to get GitHub issue forms working. There’s no validator, and no way to preview on a PR, so we’re doing it live 😅 
N/A
N/A

ci: Fix issue templates

---

.changeset/clean-phones-deliver.md
packages/openapi-typescript/examples/simple-example.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/transform/schema-object/array.test.ts
packages/openapi-typescript/test/transform/schema-object/object.test.ts

Closes #2048
The previous union+tuples generation implementation was a little hair-ball, and difficult for me to parse, so I replaced it with a stepped implementation, returning early with results whenever possible.
- first returning the full min + max union-of-tuples if possible; each union member may be `readonly`, but not the union as a whole
- next, returning the min tuple if possible; the tuple as a whole may be `readonly`, as well as its spread members.
- finally, returning the simple array type, which may be `readonly`
Here's a simple schema, and the before+after generated types.
```yaml
components:
schemas:
TwoNumbers:
type: array
items:
type: number
minItems: 1
maxItems: 2
```
```ts
// Before
export interface components {
schemas: {
TwoNumbers: [
] | [
number
];
};
…
// After …
```

Fix prefixItems / minItems / maxItems tuple generation

---

.changeset/four-worms-leave.md
docs/6.x/node.md
packages/openapi-typescript/src/transform/components-object.ts
packages/openapi-typescript/src/transform/index.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/node-api.test.ts

Closes #2013
* Make sure `TransformNodeOptions` is extension is acceptable.
* Decide whether `schema` should be populated for `transform` options; it's redundant since the first argument to transform is already the schema node, but it introduces consistency between the `transform` and `postTrannsform` APIs that I think might be desirable.

Add schema to postTransform options

---

.changeset/funny-beans-film.md
.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/size-limit.yml
docs/package.json
package.json
packages/openapi-fetch/examples/react-query/package.json
packages/openapi-fetch/examples/sveltekit/package.json
packages/openapi-fetch/examples/vue-3/package.json
packages/openapi-fetch/package.json
packages/openapi-metadata/package.json
packages/openapi-react-query/package.json
packages/openapi-typescript/package.json
packages/swr-openapi/package.json
pnpm-lock.yaml

chore: Bump deps

---

.changeset/chilly-meals-act.md
packages/openapi-react-query/src/index.ts
packages/openapi-react-query/test/index.test.tsx

Resolves #1845 #1949
See added test. When adding the select option, `useQuery` and `useSuspenseQuery` now infers the correct type when using the `select` transformer.
Example: 
```ts
client.useQuery(
"get",
"/string-array",
{},
{
select: () => 1, // resolves to type number
},
),
```
```ts
client.useQuery(
"get",
"/string-array",
{},
{
select: (data) => [data], // resolves to type `data[]`
},
),
```
```ts
client.useQuery("get","/string-array") // still infers correct data (no change)
```

fix(openapi-react-query): correctly infer select return value

---

packages/openapi-react-query/src/index.ts
packages/openapi-react-query/test/index.test.tsx

Following suit from https://github.com/openapi-ts/openapi-typescript/pull/1831, this PR adds the ability to get the return type of an endpoint from a `OpenapiQueryClient` client.
The rationale implements the same behaviours as the referenced PR, only changing expected type for the incoming client to be compliant with the `OpenapiQueryClient` interface (which doesn't extend `Client`).

add MethodResponse for openapi-react-query

---

.changeset/mighty-comics-worry.md
packages/openapi-react-query/src/index.ts
packages/openapi-react-query/test/fixtures/api.d.ts
packages/openapi-react-query/test/fixtures/api.yaml
packages/openapi-react-query/test/index.test.tsx

close https://github.com/openapi-ts/openapi-typescript/issues/1828
I added useInfiniteQuery() to openapi-react-query.
Any feedback is welcome. I'll review it and make updates!
This is a continuation work of #1881

feat(openapi-react-query): support for useInfiniteQuery()

---

.changeset/purple-walls-repeat.md
docs/cli.md
packages/openapi-typescript/bin/cli.js
packages/openapi-typescript/src/index.ts
packages/openapi-typescript/src/transform/parameters-array.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/fixtures/generate-params-test.yaml
packages/openapi-typescript/test/index.test.ts
packages/openapi-typescript/test/test-helpers.ts

https://github.com/openapi-ts/openapi-typescript/issues/2103
Use openapi-typescript to convert a schema that has missing path paramaters definitions.

feat(openapi-typescript): generate path params flag

---

.changeset/witty-bottles-carry.md
packages/openapi-react-query/package.json

This pull request closes #2098. `exports.require.types` was pointing to a file that does not exist. It now points to the same `exports.imports.types` file (`index.d.ts`) fixing type issues when using this library with `require`. 
Types should properly resolved when using a `require` import.

fix: use index.d.ts as types for cjs

---

.changeset/sour-steaks-double.md
packages/openapi-react-query/src/index.ts
packages/openapi-react-query/test/index.test.tsx

For urls that do not include an init param, generate a query key of length 2. This allows the value to be passed directly to `invalidateQueries()`.
Without this change, the package generates `["get", "/foo", undefined]` which does not correctly match the corresponding get query.
Related to https://github.com/openapi-ts/openapi-typescript/issues/1806
This doesn't quite solve the problem when there are init params but at least solves for the case where there are no params...

Drop init argument when not needed in query key

---

.changeset/ninety-starfishes-speak.md
packages/openapi-typescript/package.json
pnpm-lock.yaml

I updated `@redocly/openapi-core` to [v1.28.0](https://github.com/Redocly/redocly-cli/releases/tag/%40redocly%2Fopenapi-core%401.28.0). This update [removes](https://github.com/Redocly/redocly-cli/pull/1848) deprecated use of `punycode`, which should clean up everyone's log output when running `openapi-typescript` 🎉
Fixes #1939.

Update @redocly/openapi-core to 1.28.0

---

.changeset/breezy-bottles-mix.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/http-methods/head.test.ts

- This PR fixes how HEAD method requests are handled in openapi-fetch by preventing body parsing regardless of the Content-Length header value.
- [According to RFC 9110,](https://httpwg.org/specs/rfc9110.html#HEAD) HEAD responses should have the same metadata as GET but must not include a body. 
Previously, the library only handled this correctly when Content-Length was "0", causing JSON parsing errors in other cases.
- Fixes #2195.
- Check that the condition now properly skips body parsing for HEAD requests
- Verify the new test case ensures HEAD requests with non-zero Content-Length are handled correctly

fix(openapi-fetch): prevent body parsing for HEAD requests regardless of Content-Length

---

packages/openapi-fetch/examples/sveltekit/README.md

Docs. Broken links (or redirecting) and broken url to page example.
Just docs.

chore(docs): Update svelte urls and internal example link

---

.changeset/clever-worms-smile.md
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/transform/schema-object/object.test.ts

This PR adds support for boolean property schemas, ie:
```json
{
"type": "object",
"properties": {
"truthy": true,
"falsy": false
}
}
```
The PR changes the flow in the loop handling object properties to reach "edge-case" handling that was already present for boolean schemas. This was previously not reached due to an early error that was thrown if the property schema was not an object. Properties that were previously accessed directly from the schema object are now extracted conditionally before hand.
Closes #2198.
See the added test case for details.

Fix boolean props

---

.changeset/wet-cougars-behave.md
packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/test/node-api.test.ts

The current declaration of the enhanced `ReadonlyArray` type uses the [undesired](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any) `any` type instead of the more appropriate `unknown` type.

Replacing `any` with `unknown` in the `ReadonlyArray` type declaration.

---

.changeset/little-meals-hide.md
packages/openapi-typescript/src/transform/paths-enum.ts
packages/openapi-typescript/test/transform/paths-enum.test.ts

Fixes: https://github.com/openapi-ts/openapi-typescript/issues/2101, when the --make-paths-enum was reintroduced back it was reintroduced with previously fixed bug: https://github.com/openapi-ts/openapi-typescript/issues/950
It's straight-forward change :)

fix(openapi-typescript): --make-paths-enum renames the paths URL

---

packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/src/transform/response-object.ts

This PR adds JSDoc comments like `@example` to response objects. We are missing them in our generated types. They are already present on request objects and in many other places.
See changes in `examples/digital-ocean-api.ts` below.

feat(openapi-typescript): add jsdoc comments to response object

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/size-limit.yml
docs/package.json
package.json
packages/openapi-fetch/examples/nextjs/package.json
packages/openapi-fetch/examples/sveltekit/package.json
packages/openapi-fetch/examples/vue-3/package.json
packages/openapi-fetch/package.json
packages/openapi-metadata/package.json
packages/openapi-react-query/package.json
packages/openapi-typescript-helpers/package.json
packages/openapi-typescript/package.json
packages/swr-openapi/package.json
pnpm-lock.yaml

Chore: updates deps to satisfy renovate and dependabot warnings. No critical security issues fixed, mostly just noise from docs, examples, tests, etc.
Updates to pnpm 10 which should be an invisible change.
N/A
- Tests will fail if any problems

chore: update deps, upgrade to pnpm 10

---

docs/swr-openapi/use-immutable.md
docs/swr-openapi/use-infinite.md

Fixes import paths in the example snippets

Fix import paths in swr-openapi docs

---

.github/workflows/ci.yml

Node 18 is end-of-life as of April 30. Remove from CI.
This doesn’t mean we’re dropping support per se—it should continue to work for a while. But don’t spend CI minutes testing it.
- CI will catch errors

chore: remove Node 18

---

.changeset/seven-monkeys-fetch.md
docs/.vitepress/en.ts
docs/openapi-react-query/use-infinite-query.md
packages/openapi-react-query/src/index.ts
packages/openapi-react-query/test/index.test.tsx

Updates the types for `useInfiniteQuery` to infer the return type from the `select` option, if provided. Adds onto #2105 with recent addition of #2117.
Also adds the docs for `useInfiniteQuery` to the navigation in the docs site, it wasn't being linked to, and adds a note about customizing the query param name for pagination.
See previous PR for the type inference in #2105 and additional test added to the `useInfiniteQuery` suite to check the return type is correctly inferred and functionally sound from useInfiniteQuery.

Infer Return Type for `select` from `useInfiniteQuery`

---

.changeset/heavy-onions-bake.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/path-based-client/path-based-client.test.ts

When using `wrapAsPathBasedClient` to access methods of client dynamically it was throwing an error as `this` context was not assigned to `PathCallForwarder` class.
Rewriting `PathCallForwarder` to use arrow function fixes the issue.
I've added a test case which has example how `wrapAsPathBasedClient` can be used in generic function to retrieve methods, which also verifies the fix.

fix(openapi-fetch): dynamic access to methods using wrapAsPathBasedClient

---

.changeset/mean-colts-hunt.md
packages/openapi-metadata/src/utils/metadata.ts
packages/openapi-metadata/test/utils/metadata.test.ts

This pull request closes #2123 by improving the thunk detection regex `() => User`.
A new added test that was failing before is now passing properly with new changes.

fix(metadata): fix thunk type detection

---

packages/openapi-typescript/examples/digital-ocean-api.ts
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/test/transform/schema-object/string.test.ts

Fixes #2144
Fixes #2055
Pretty straightforward PR

Don't remove `null` type if a default is present.

---

packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/common/create-client.test.ts

Fixes: https://github.com/openapi-ts/openapi-typescript/issues/2156

fix(openapi-fetch): fix overriding baseUrl per request without overriding default baseUrl

---

packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/src/transform/parameters-array.ts
packages/openapi-typescript/test/fixtures/parameters-test.yaml
packages/openapi-typescript/test/index.test.ts
packages/openapi-typescript/test/lib/ts.test.ts
packages/openapi-typescript/test/transform/webhooks-object.test.ts

Refs into the parameters array are turned into invalid indexes into the `paths` structure.
The problematic behavior is triggered using a $ref that points into the `parameters` array.
The problematic generated type then tries to index into `["parameters"]["0"]` as though it were an array, when in fact it should be indexing into `["parameters"]["query"]`.
This particular weird ref was generated when I bundled a big schema with [@apidevtools/json-schema-ref-parser](https://github.com/APIDevTools/json-schema-ref-parser/blob/main/docs/ref-parser.md#the-refparser-class).
* While parsing `oapiRefs` from parameters arrays, pass the resolved ParameterObject and use its `in` method to index into `parameters` type.
This probably doesn't work for more complex $refs, but I think it does slightly …

Fix invalid $ref index into path

---

packages/openapi-react-query/src/index.ts
packages/openapi-react-query/test/index.test.tsx

I created an issue about how 204 status codes are handled and an error that's thrown by react-query due to data being returned as undefined (Something that react-query does not support for it's queryFn's).
Issue: https://github.com/openapi-ts/openapi-typescript/issues/2234
This PR handles 204 or zero Content-Length header by returning data as null in the queryFn.
Use the useQuery hook towards an API endpoint that returns a 204 status or zero value in the Content-Length header, the data should be set to null and no error should be thrown.

React query handle 204 or zero content length

---

packages/swr-openapi/src/__test__/types.test-d.ts
packages/swr-openapi/src/infinite.ts
packages/swr-openapi/src/query-base.ts

close #2136 
Added a new Type Parameter, ``FetcherError``, to ``createQueryHook``, ``createImmutableHook``, and ``createInfiniteHook``.
It allows you to include ``FetcherError`` to the type of the error in the return value of ``useQuery``.
By default, it is set to ``never`` to maintain backward compatibility.
Why this is needed is detailed in issue #2136 .
To avoid breaking VSCode syntax highlighting, ``"<unique-key>"`` is assigned to a variable before being used in the type argument.

feat(swr-openapi): add custom error types to query builder

---

docs/openapi-fetch/api.md
packages/openapi-fetch/src/index.js
packages/openapi-fetch/test/common/request.test.ts

Fixes #2069 
This PR updates the `defaultBodySerializer` to correctly serialize the body if `Content-Type` header is set to `x-www-form-urlencoded`. This is useful for OAuth2 token requests.
I'm not sure about the headers: what type are they, and are they normalized?
I added handling for both a plain JS object (`headers['Accept-Content']`) and a [`Headers`](https://developer.mozilla.org/en-US/docs/Web/API/Headers/get) object (`headers.get['Accept-Content']`), as well as both capitalized and lower-case versions.

Encode the request body if `Content-Type` header is `x-www-form-urlencoded`

---

.changeset/bumpy-parrots-lie.md
package.json
packages/openapi-fetch/src/index.js
packages/openapi-metadata/package.json
pnpm-lock.yaml

Followup from #2096, also passes in mergedHeaders to the bodySerializer so we’re not dropping user-set headers.
- Tests should pass
No tests updated; this should be an invisible change

Improve header handling

---

docs/CONTRIBUTING.md

This small PR fixes the `CODE_OF_CONDUCT.md` reference.

Update code of conduct source

---

docs/openapi-fetch/middleware-auth.md

Fix snippet for Handling statefulness in `openapi-fetch/middleware-auth` page
Check snippet in IDE

Fix snippet for Handling statefulness in `openapi-fetch/middleware-auth` page

---

.changeset/seven-eyes-lie.md
packages/openapi-typescript/examples/simple-example.ts
packages/openapi-typescript/src/lib/ts.ts
packages/openapi-typescript/test/lib/ts.test.ts

Implements https://github.com/openapi-ts/openapi-typescript/issues/2371
Add JSDoc support for the recommended `examples` array on JSON Schema objects. Previously, only examples in the singular `example` property were added to the JSDoc, and now all examples in the `examples` array are also added as separate examples.
The code change was very minor, but since many of the example specs used `examples` already, the snapshots were updated in many places.
- [n/a] `docs/` updated (if necessary)

feat(openapi-typescript): support JSDoc examples from JSON schema examples array

---

docs/openapi-fetch/api.md

This PR fixes a typo in example of using `application/x-www-form-urlencoded` content type.

docs: fix typo in example

---

docs/scripts/update-contributors.js

Adds GitHub token to API requests, if present.
We should not merge this until the personal access token is approved.

Add github token auth

---

.changeset/eleven-shoes-mate.md
packages/openapi-typescript/src/transform/schema-object.ts
packages/openapi-typescript/src/types.ts
packages/openapi-typescript/test/transform/schema-object/object.test.ts

Add support for patternProperties in addition to additionalProperties (#754).
Building on the work of @gzm0 in [1901](https://github.com/openapi-ts/openapi-typescript/pull/1901) by adding tests
Ran the command `pnpm run update:examples` which created 129 new files and updated 69, none of which seemed related to this change. Let me know if you wan't me to do it anyways.
Refer to comments in original [PR 1901](https://github.com/openapi-ts/openapi-typescript/pull/1901)
Validate tests are satisfactory

Feat: Add support for pattern properties
